#!/usr/bin/env python3

# Copyright (C) The btclib developers
#
# This file is part of btclib. It is subject to the license terms in the
# LICENSE file found in the top-level directory of this distribution.
#
# No part of btclib including this file, may be copied, modified, propagated,
# or distributed except according to the terms contained in the LICENSE file.
"""Elliptic curve classes and functions."""

from __future__ import annotations

import json
from collections.abc import Sequence
from hashlib import sha256
from math import sqrt
from os import path
from typing import Any

from btclib_libsecp256k1.mult import mult as libsecp256k1_mult

from btclib.alias import HashF, Integer, Point
from btclib.curves.curve_group import (
    HEX_THRESHOLD,
    CurveGroup,
    _mult,
    _multi_mult,
    jac_from_aff,
)
from btclib.curves.curve_group_2 import (
    double_mult_w_NAF,
    mult_endomorphism_secp256k1,
)
from btclib.exceptions import BTClibValueError
from btclib.utils import hex_string, int_from_integer


class CurveSubGroup(CurveGroup):
    """Subgroup of the points of an elliptic curve over Fp generated by G."""

    def __init__(self, p: Integer, a: Integer, b: Integer, G: Point) -> None:
        super().__init__(p, a, b)

        # 2. check that xG and yG are integers in the interval [0, p−1]
        # 4. Check that yG^2 = xG^3 + a*xG + b (mod p)
        if len(G) != 2:
            raise BTClibValueError("generator must be a sequence[int, int]")
        self.G = (int_from_integer(G[0]), int_from_integer(G[1]))
        if not self.is_on_curve(self.G):
            raise BTClibValueError("Generator is not on the curve")
        self.GJ = self.G[0], self.G[1], 1  # Jacobian coordinates

    def __str__(self) -> str:
        result = super().__str__()
        if self.p > HEX_THRESHOLD:
            result += f"\n x_G = {hex_string(self.G[0])}"
            result += f"\n y_G = {hex_string(self.G[1])}"
        else:
            result += f"\n x_G = {self.G[0]}"
            result += f"\n y_G = {self.G[1]}"
        return result

    def __repr__(self) -> str:
        result = super().__repr__()[:-1]
        if self.p > HEX_THRESHOLD:
            result += f", ('{hex_string(self.G[0])}', '{hex_string(self.G[1])}')"
        else:
            result += f", ({self.G[0]}, {self.G[1]})"
        result += ")"
        return result

    def _eq_key(self) -> tuple[int, ...]:
        return super()._eq_key() + self.G


class Curve(CurveSubGroup):
    """Prime order subgroup of the points of an elliptic curve over Fp."""

    def __init__(
        self,
        p: Integer,
        a: Integer,
        b: Integer,
        G: Point,
        n: Integer,
        cofactor: int,
        weakness_check: bool = True,
        order_check: bool = True,
        name: str | None = None,
    ) -> None:
        super().__init__(p, a, b, G)
        n = int_from_integer(n)

        # Security level is expressed in bits, where n-bit security
        # means that the attacker would have to perform 2^n operations
        # to break it. Security bits are half the key size for asymmetric
        # elliptic curve cryptography, i.e. half of the number of bits
        # required to express the group order n or, holding Hasse theorem,
        # to express the field prime p

        self.n = n
        self.nlen = n.bit_length()
        self.n_size = (self.nlen + 7) // 8

        # 5. Check that n is prime.
        if n < 2 or n % 2 == 0 or pow(2, n - 1, n) != 1:
            err_msg = "n is not prime: "
            err_msg += f"{hex_string(n)}" if n > HEX_THRESHOLD else f"{n}"
            raise BTClibValueError(err_msg)
        delta = int(2 * sqrt(self.p))
        # also check n with Hasse Theorem
        if cofactor < 2 and not self.p + 1 - delta <= n <= self.p + 1 + delta:
            err_msg = "n not in p+1-delta..p+1+delta: "
            err_msg += f"{hex_string(n)}" if n > HEX_THRESHOLD else f"{n}"
            raise BTClibValueError(err_msg)

        # 7. Check that G ≠ INF, nG = INF
        if self.G[1] == 0:
            err_msg = "INF point cannot be a generator"
            raise BTClibValueError(err_msg)
        # n*G is by far the most expensive check here -- a python
        # double-and-add over nlen bits -- and it dominates the cost of
        # building a curve: at import time the 27 catalogued curves would
        # spend ~118 ms of ~168 ms on it, against ~2 ms for the
        # primality of n. The catalogue therefore passes
        # order_check=False, as it does weakness_check=False below: its
        # parameters are constants, and test_catalogued_curves rebuilds
        # every one of them from the json data with both checks on, while
        # tests/curves/curve_group_test.py and curve_group_2_test.py assert
        # n*G == INF for every curve of CURVES through ten distinct mult
        # implementations. It stays on by default all the same, and is not
        # merely a test-time luxury: a caller-defined curve whose n is
        # not the order of G is accepted by every other check here and
        # then fails silently downstream, mult and sign returning
        # answers in a group nobody asked for
        if order_check and _mult(n, self.GJ, self)[2] != 0:
            err_msg = "n is not the group order: "
            err_msg += f"{hex_string(n)}" if n > HEX_THRESHOLD else f"{n}"
            raise BTClibValueError(err_msg)

        # 6. Check cofactor
        exp_cofactor = int(1 / n + delta / n + self.p / n)
        if cofactor != exp_cofactor:
            err_msg = f"invalid cofactor: {cofactor}, expected {exp_cofactor}"
            raise BTClibValueError(err_msg)
        self.cofactor = cofactor

        # 8. Check that n ≠ p
        # self.p, not the p parameter: that one is still an Integer, and
        # every curve of this library's own catalogue spells it as a hex
        # string, so the comparison would be int == str -- false whatever
        # the curve. What it must reject is an anomalous curve, #E = p,
        # whose logarithm transfers to addition in F_p and is
        # polynomial-time (Smart, Semaev, Satoh-Araki), and the MOV check
        # below cannot catch it either: pow(self.p, i, n) with n == p is
        # 0, never 1 (issue #166)
        if n == self.p:
            raise BTClibValueError(f"n=p weak curve: {hex_string(n)}")

        if weakness_check:
            # 8. Check that p^i % n ≠ 1 for all 1≤i<100
            # 99 modular exponentiations, the second cost of building a
            # curve once n*G is gated: 5.2 ms of the 9.7 ms the catalogue
            # would spend at import time. Skipped for it on the same grounds,
            # and re-run by test_catalogued_curves; on by default, since
            # what it rejects is a curve whose embedding degree makes the
            # MOV attack carry the discrete logarithm into a field where
            # it is easy -- and nothing downstream would notice
            for i in range(1, 100):
                if pow(self.p, i, n) == 1:
                    raise UserWarning("weak curve")

        self.name = name

    def __str__(self) -> str:
        result = super().__str__()
        if self.n > HEX_THRESHOLD:
            result += f"\n n   = {hex_string(self.n)}"
        else:
            result += f"\n n   = {self.n}"
        result += f"\n cofactor = {self.cofactor}"
        return result

    def __repr__(self) -> str:
        result = super().__repr__()[:-1]
        if self.n > HEX_THRESHOLD:
            result += f", '{hex_string(self.n)}'"
        else:
            result += f", {self.n}"
        result += f", {self.cofactor}"
        result += ")"
        return result

    def _eq_key(self) -> tuple[int, ...]:
        # name is not part of the curve: the same curve is catalogued as
        # secp256r1 by SEC 2 and as P-256 by NIST, and weakness_check and
        # order_check are construction-time options, not parameters
        return (*super()._eq_key(), self.n, self.cofactor)


datadir = path.join(path.dirname(__file__), "_data")


def _catalogued_curve(params: list[Any], name: str) -> Curve:
    """Build one curve of the shipped catalogue, from its json parameters.

    One function for the four catalogues, so that the flags cannot drift
    apart. Both expensive checks are off: these parameters are the
    standardized constants of SEC 2, FIPS 186-4 and RFC 5639, and
    re-deriving from them at every interpreter start that n is the order
    of G, and that the curve is not MOV-weak, would cost 118 ms and 5 ms
    of a ~168 ms module import. What is verified once, by
    test_catalogued_curves rebuilding each curve from the same json data
    with both checks on, does not have to be verified again on the way to
    every signature.
    """
    p, a, b, G, n, cofactor = params
    return Curve(
        p, a, b, G, n, cofactor, weakness_check=False, order_check=False, name=name
    )


# Elliptic Curve Cryptography (ECC)
# Brainpool Standard Curves and Curve Generation
# https://www.rfc-editor.org/rfc/rfc5639.html
filename = path.join(datadir, "ec_Brainpool.json")
with open(filename, encoding="ascii") as file_:
    Brainpool_params2 = json.load(file_)
Brainpool: dict[str, Curve] = {
    ec_name: _catalogued_curve(Brainpool_params2[ec_name], ec_name)
    for ec_name in Brainpool_params2
}
# FIPS PUB 186-4
# FEDERAL INFORMATION PROCESSING STANDARDS PUBLICATION
# Digital Signature Standard (DSS)
# https://oag.ca.gov/sites/all/files/agweb/pdfs/erds1/fips_pub_07_2013.pdf
filename = path.join(datadir, "ec_NIST.json")
with open(filename, encoding="ascii") as file_:
    NIST_params2 = json.load(file_)
NIST: dict[str, Curve] = {
    ec_name: _catalogued_curve(NIST_params2[ec_name], ec_name)
    for ec_name in NIST_params2
}
# SEC 2 v.1 curves, removed from SEC 2 v.2 as insecure ones
# http://www.secg.org/SEC2-Ver-1.0.pdf
filename = path.join(datadir, "ec_SEC2v1_insecure.json")
with open(filename, encoding="ascii") as file_:
    SEC2v1_params2 = json.load(file_)
SEC2v1: dict[str, Curve] = {
    ec_name: _catalogued_curve(SEC2v1_params2[ec_name], ec_name)
    for ec_name in SEC2v1_params2
}
# curves included in both SEC 2 v.1 and SEC 2 v.2
# http://www.secg.org/sec2-v2.pdf
filename = path.join(datadir, "ec_SEC2v2.json")
with open(filename, encoding="ascii") as file_:
    SEC2v2_params2 = json.load(file_)
SEC2v2: dict[str, Curve] = {}
for ec_name in SEC2v2_params2:
    # one object in both catalogues, not two: building the curve twice
    # would hand out two objects, and only one of them the secp256k1 the
    # libsecp256k1 dispatch below compares against
    SEC2v2[ec_name] = _catalogued_curve(SEC2v2_params2[ec_name], ec_name)
    SEC2v1[ec_name] = SEC2v2[ec_name]

# a new dict, deliberately: aliasing (CURVES = SEC2v1) followed by
# update() calls would pour NIST and Brainpool into the SEC 2 v.1
# catalogue -- SEC2v1 with 27 entries instead of its own 15, and
# SEC2v1["nistp256"] answering a curve that is not in SEC 2 v.1 at all.
# Each catalogue holds what it is named after
CURVES = SEC2v1 | NIST | Brainpool

secp256k1 = CURVES["secp256k1"]


def _libsecp256k1_applicable(ec: Curve, hf: HashF | None = None) -> bool:
    """Return True if the libsecp256k1 bindings can serve ec and hf.

    Every dispatch to the bindings asks here, so that the predicates
    cannot drift apart the way hand-written copies would; a caller
    with a further condition of its own -- mult, whose bindings take the
    generator and a non-zero scalar alone -- ands it on top.

    hf is compared by identity, deliberately: nothing short of running
    the two functions tells sha256 from a look-alike, so a wrapper such
    as functools.partial(sha256) falls back to the python path. That is
    the conservative direction -- slower, never wrong.
    """
    if ec != secp256k1:
        return False
    return hf is None or hf is sha256


def mult(m_int: Integer, Q: Point | None = None, ec: Curve = secp256k1) -> Point:
    """Elliptic curve scalar multiplication."""
    m: int = int_from_integer(m_int) % ec.n

    # m == 0 is the infinity point, which the bindings reject as a scalar
    if m and _libsecp256k1_applicable(ec) and (Q is None or Q == ec.G):
        return libsecp256k1_mult(m)

    if Q is None:
        QJ = ec.GJ
    else:
        ec.require_on_curve(Q)
        QJ = jac_from_aff(Q)

    # past the check above, secp256k1 here means a point the bindings do
    # not take -- any point but the generator -- which is exactly where
    # the GLV endomorphism pays: 1.03 ms against the 1.52 of _mult, the
    # decomposition being secp256k1's own lambda and beta. Same predicate
    # as the bindings dispatch, so the two cannot drift apart
    R = (
        mult_endomorphism_secp256k1(m, QJ, ec)
        if _libsecp256k1_applicable(ec)
        else _mult(m, QJ, ec)
    )
    return ec.aff_from_jac(R)


def double_mult(
    u: Integer, H: Point, v: Integer, Q: Point, ec: Curve = secp256k1
) -> Point:
    """Double scalar multiplication (u*H + v*Q)."""
    ec.require_on_curve(H)
    HJ = jac_from_aff(H)

    ec.require_on_curve(Q)
    QJ = jac_from_aff(Q)

    u = int_from_integer(u) % ec.n
    v = int_from_integer(v) % ec.n
    R = double_mult_w_NAF(u, HJ, v, QJ, ec)
    return ec.aff_from_jac(R)


def multi_mult(
    scalars: Sequence[Integer], points: Sequence[Point], ec: Curve = secp256k1
) -> Point:
    """Return the multi scalar multiplication u1*Q1 + ... + un*Qn.

    Use Bos-Coster's algorithm for efficient computation.
    """
    if len(scalars) != len(points):
        err_msg = "mismatch between number of scalars and points: "
        err_msg += f"{len(scalars)} vs {len(points)}"
        raise BTClibValueError(err_msg)

    ints = [int_from_integer(s) % ec.n for s in scalars]
    for Q in points:
        ec.require_on_curve(Q)
    jac_points = [jac_from_aff(Q) for Q in points]

    R = _multi_mult(ints, jac_points, ec)
    return ec.aff_from_jac(R)
