# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""The prime-order Curve and the multiplications built on it.

mult, double_mult_var and multi_mult_var dispatch secp256k1 to the
libsecp256k1 bindings and answer every other curve -- and the cases
the bindings cannot express -- with curve_group's arithmetic.

What this module exports is the class, the three multiplications, the
catalogue, the four standards it is the union of -- which is where
btclib.curves keeps them, a standard being a question about a curve and
not a way of finding one -- and the `*_params2` each of those four is
built from, which is what test_catalogued_curves rebuilds every curve
out of with both expensive checks on.

`datadir` stays out: it is where this package keeps the four json files
loaded below, so it answers a question about the installation rather than
about a curve, and `btclib.network` has a `datadir` of its own for the
network files. The loader's own names are underscored, a `with` target and
a `for` target being module globals like any other.
"""

from __future__ import annotations

import contextlib
import json
from collections.abc import Sequence
from hashlib import sha256
from math import isqrt
from pathlib import Path
from typing import Any

from btclib_secp256k1.keys import parse as libsecp256k1_pubkey_parse
from btclib_secp256k1.keys import pubkey_combine as libsecp256k1_pubkey_combine
from btclib_secp256k1.keys import pubkey_tweak_mul as libsecp256k1_pubkey_tweak_mul
from btclib_secp256k1.keys import serialize as libsecp256k1_pubkey_serialize
from btclib_secp256k1.mult import mult as libsecp256k1_mult

from btclib.alias import INF, HashF, Integer, JacPoint, Point
from btclib.curves.curve_group import (
    HEX_THRESHOLD,
    CurveGroup,
    _blinded_jac,
    _is_prime,
    _jac_from_aff,
    _mult,
    _mult_fixed_base,
    _multi_mult_var,
)
from btclib.curves.curve_group_2 import (
    _double_mult_endomorphism_secp256k1_var,
    _double_mult_w_NAF_var,
    _mult_endomorphism_secp256k1,
)
from btclib.exceptions import BTClibValueError
from btclib.number_theory import legendre_symbol_var
from btclib.utils import hex_string, int_from_integer

__all__ = [
    "CURVES",
    "NIST",
    "Brainpool",
    "Brainpool_params2",
    "Curve",
    "NIST_params2",
    "SEC2v1",
    "SEC2v1_params2",
    "SEC2v2",
    "SEC2v2_params2",
    "double_mult_var",
    "mult",
    "multi_mult_var",
    "secp256k1",
]


def _generator_from_point(G: Point, ec: CurveGroup) -> Point:
    """Return the generator, checked against the group it must lie in.

    SEC 1 v.2 3.1.1.2.1 steps 2 and 4: the coordinates are integers in
    0..p-1, and they solve the curve equation. `ec` is the group under
    construction, which has its p, a and b by the time this is asked.
    """
    if len(G) != 2:
        raise BTClibValueError("generator must be a sequence[int, int]")
    point = int_from_integer(G[0]), int_from_integer(G[1])
    if not ec.is_on_curve(point):
        raise BTClibValueError("Generator is not on the curve")
    return point


def _assert_mov_resistant(p: int, n: int) -> None:
    """Refuse a curve whose embedding degree is under 100.

    SEC 1 v.2 3.1.1.2.1 step 8: p^i ≠ 1 (mod n) for 1 <= i < 100, which
    rejects the curves whose logarithm the MOV attack carries into an
    extension field where it is easy, and nothing downstream would notice.

    Its 99 modular exponentiations are the second cost of building a
    curve, once nG is gated: 5.2 ms of the 9.7 ms the catalogue would
    spend at import time, which is why the catalogue passes
    weakness_check=False and test_catalogued_curves runs it instead.

    A BTClibValueError, as every other rejection in this constructor is:
    the embedding degree is a parameter of the curve being refused, so
    the caller that catches an unusable `n` catches this one too. The
    n == p check below is the other weak-curve refusal, and the two
    disagreeing on their class is what left this one uncatchable for
    anyone holding the library to its own exception contract.
    """
    for i in range(1, 100):
        if pow(p, i, n) == 1:
            err_msg = "weak curve: the embedding degree is "
            err_msg += f"{i}, which is below 100"
            raise BTClibValueError(err_msg)


class Curve(CurveGroup):
    """Cyclic subgroup of prime order n, generated by G, of the curve points.

    The subgroup is ⟨G⟩ = {INF, G, 2G, …, (n-1)G}, of prime order n,
    inside the group of all the points of the curve — the `CurveGroup`
    this is built on, whose order is n times the cofactor h. The curve is
    that group and this is a subgroup of it, so the name is the wrong way
    round on purpose: this is the only group anything else in btclib
    multiplies in, and `Curve` is what a caller asks for.

    Two things follow from n being prime, and btclib.ecc relies on both:
    the integers modulo n are a field, so every scalar but zero has an
    inverse — the nonce and s that ecdsa inverts, the challenge that ssa's
    key recovery does — and the subgroup has no subgroup other than itself
    and {INF}, so every point of it but INF is a generator and no
    confinement to a small subgroup is possible.

    n is a parameter and not a computed quantity: the order of G is the
    order of the whole group divided by the index of ⟨G⟩ in it, and
    counting the points of a curve this size is Schoof-Elkies-Atkin rather
    than arithmetic on p, a and b. What the constructor does compute is
    that the parameter *is* the order, and that is where the primality of
    n earns its second keep. nG = INF proves only that n annihilates G,
    i.e. that the order of G divides n; pinning it to n in general asks
    for (n/q)G ≠ INF for every prime q dividing n, which is the
    factorization of n — a number no curve publishes alongside its
    parameters. With n prime and G ≠ INF the single nG = INF is the whole
    of it.

    Which is also why the two classes are the whole hierarchy, with no
    third one between them for the cyclic subgroup of unstated order:
    ⟨G⟩ carrying an n it cannot verify, or no n at all, is a cyclic group
    that cannot say how many elements it has, cannot reduce a scalar, and
    cannot bound a private key. Nothing here could take one as an
    argument.
    """

    def __init__(
        self,
        p: Integer,
        a: Integer,
        b: Integer,
        G: Point,
        n: Integer,
        cofactor: int,
        weakness_check: bool = True,
        order_check: bool = True,
        name: str | None = None,
    ) -> None:
        super().__init__(p, a, b)

        self.G = _generator_from_point(G, self)
        self.GJ = self.G[0], self.G[1], 1  # Jacobian coordinates
        # the generator and its opposite are what a verification hands the
        # same on every call, so their wNAF tables are memoized and held
        # wide; _cached_odd_multiples_aff says what that buys. The
        # endomorphism's images of the two are fixed as well and are added
        # by _double_mult_endomorphism_secp256k1_var, which is what forms them
        self._fixed_points = frozenset({self.GJ, self.negate_jac(self.GJ)})

        n = int_from_integer(n)

        # Security level is expressed in bits, where n-bit security
        # means that the attacker would have to perform 2^n operations
        # to break it. Security bits are half the key size for asymmetric
        # elliptic curve cryptography, i.e. half of the number of bits
        # required to express the group order n or, holding Hasse theorem,
        # to express the field prime p

        self.n = n
        self.nlen = n.bit_length()
        self.n_size = (self.nlen + 7) // 8
        # a scalar here is reduced mod n and not mod the order of the whole
        # curve, so nlen is a tighter bound than the plen + 1 CurveGroup
        # took from Hasse -- one window less at w=4 on secp256k1, and
        # log2(cofactor) bits less on a curve with a cofactor.
        # _mult_regular_window fixes its digit count to it, and reads it
        # under this name rather than as nlen so that a CurveGroup, which
        # has no n, can be multiplied in as well
        self.scalar_len = self.nlen

        # 5. Check that n is prime.
        if not _is_prime(n):
            err_msg = "n is not prime: "
            err_msg += f"{hex_string(n)}" if n > HEX_THRESHOLD else f"{n}"
            raise BTClibValueError(err_msg)
        # Hasse's half-width, floor(2*sqrt(p)), in integer arithmetic:
        # math.sqrt rounds p to 53 bits of mantissa before the truncation,
        # which on a 256-bit p overshoots by one and widens the interval
        # below by that much. isqrt(4*p) and not 2*isqrt(p): the two are
        # the same number only when p is a perfect square, floor(2*sqrt(p))
        # being what this is -- on p = 7 they are 5 and 4, and the second
        # refuses an n of 13 that Hasse admits
        delta = isqrt(4 * self.p)
        # also check n with Hasse Theorem
        if cofactor < 2 and not self.p + 1 - delta <= n <= self.p + 1 + delta:
            err_msg = "n not in p+1-delta..p+1+delta: "
            err_msg += f"{hex_string(n)}" if n > HEX_THRESHOLD else f"{n}"
            raise BTClibValueError(err_msg)

        # 7. Check that G ≠ INF, nG = INF
        if self.G[1] == 0:
            err_msg = "INF point cannot be a generator"
            raise BTClibValueError(err_msg)
        # n*G is by far the most expensive check here -- a Python
        # double-and-add over nlen bits -- and it dominates the cost of
        # building a curve: at import time the 27 catalogued curves would
        # spend ~118 ms of ~168 ms on it, against ~2 ms for the
        # primality of n. The catalogue therefore passes
        # order_check=False, as it does weakness_check=False below: its
        # parameters are constants, and test_catalogued_curves rebuilds
        # every one of them from the json data with both checks on, while
        # tests/curves/curve_group_test.py and curve_group_2_test.py assert
        # n*G == INF for every curve of CURVES through ten distinct mult
        # implementations. It stays on by default all the same, and is not
        # merely a test-time luxury: a caller-defined curve whose n is
        # not the order of G is accepted by every other check here and
        # then fails silently downstream, mult and sign returning
        # answers in a group nobody asked for
        if order_check and _mult(n, self.GJ, self)[2] != 0:
            err_msg = "n is not the group order: "
            err_msg += f"{hex_string(n)}" if n > HEX_THRESHOLD else f"{n}"
            raise BTClibValueError(err_msg)

        # 6. Check cofactor
        # floor((p + 1 + delta) / n), the upper end of the Hasse interval
        # divided by the subgroup order, in integer arithmetic for the
        # reason delta is: three float divisions of 256-bit integers each
        # round before they are added, where the quotient of a curve with
        # a cofactor of 1 sits one ulp above the integer it must truncate
        # to
        exp_cofactor = (1 + delta + self.p) // n
        if cofactor != exp_cofactor:
            err_msg = f"invalid cofactor: {cofactor}, expected {exp_cofactor}"
            raise BTClibValueError(err_msg)
        self.cofactor = cofactor

        # 8. Check that n ≠ p
        # self.p, not the p parameter: that one is still an Integer, and
        # every curve of this library's own catalogue spells it as a hex
        # string, so the comparison would be int == str -- false whatever
        # the curve. What it must reject is an anomalous curve, #E = p,
        # whose logarithm transfers to addition in F_p and is
        # polynomial-time (Smart, Semaev, Satoh-Araki), and the MOV check
        # below cannot catch it either: pow(self.p, i, n) with n == p is
        # 0, never 1 (issue #166)
        if n == self.p:
            raise BTClibValueError(f"n=p weak curve: {hex_string(n)}")

        if weakness_check:
            _assert_mov_resistant(self.p, n)

        self.name = name

    def __str__(self) -> str:
        result = super().__str__()
        # the generator is rendered as the curve is, in hex above the
        # threshold: a coordinate is the size of p, whatever its own
        # leading bits
        if self.p > HEX_THRESHOLD:
            result += f"\n x_G = {hex_string(self.G[0])}"
            result += f"\n y_G = {hex_string(self.G[1])}"
        else:
            result += f"\n x_G = {self.G[0]}"
            result += f"\n y_G = {self.G[1]}"
        if self.n > HEX_THRESHOLD:
            result += f"\n n   = {hex_string(self.n)}"
        else:
            result += f"\n n   = {self.n}"
        result += f"\n cofactor = {self.cofactor}"
        return result

    def __repr__(self) -> str:
        result = super().__repr__()[:-1]
        if self.p > HEX_THRESHOLD:
            result += f", ('{hex_string(self.G[0])}', '{hex_string(self.G[1])}')"
        else:
            result += f", ({self.G[0]}, {self.G[1]})"
        if self.n > HEX_THRESHOLD:
            result += f", '{hex_string(self.n)}'"
        else:
            result += f", {self.n}"
        result += f", {self.cofactor}"
        result += ")"
        return result

    def _eq_key(self) -> tuple[int, ...]:
        # name is not part of the curve: the same curve is catalogued as
        # secp256r1 by SEC 2 and as P-256 by NIST, and weakness_check and
        # order_check are construction-time options, not parameters. G is
        # one: it is the point every scalar is measured against, so two
        # curves differing in it hold the same points under a different
        # correspondence with the integers modulo n
        return (*super()._eq_key(), *self.G, self.n, self.cofactor)


datadir = Path(__file__).parent / "_data"


def _catalogued_curve(params: list[Any], name: str) -> Curve:
    """Build one curve of the shipped catalogue, from its json parameters.

    One function for the four catalogues, so that the flags cannot drift
    apart. Both expensive checks are off: these parameters are the
    standardized constants of SEC 2, FIPS 186-4 and RFC 5639, and
    re-deriving from them at every interpreter start that n is the order
    of G, and that the curve is not MOV-weak, would cost 118 ms and 5 ms
    of a ~168 ms module import. What is verified once, by
    test_catalogued_curves rebuilding each curve from the same json data
    with both checks on, does not have to be verified again on the way to
    every signature.
    """
    p, a, b, G, n, cofactor = params
    return Curve(
        p, a, b, G, n, cofactor, weakness_check=False, order_check=False, name=name
    )


# Elliptic Curve Cryptography (ECC)
# Brainpool Standard Curves and Curve Generation
# https://www.rfc-editor.org/rfc/rfc5639.html
_filename = datadir / "ec_Brainpool.json"
with _filename.open(encoding="ascii") as _file:
    Brainpool_params2 = json.load(_file)
Brainpool: dict[str, Curve] = {
    _ec_name: _catalogued_curve(Brainpool_params2[_ec_name], _ec_name)
    for _ec_name in Brainpool_params2
}
# FIPS PUB 186-4
# FEDERAL INFORMATION PROCESSING STANDARDS PUBLICATION
# Digital Signature Standard (DSS)
# https://oag.ca.gov/sites/all/files/agweb/pdfs/erds1/fips_pub_07_2013.pdf
_filename = datadir / "ec_NIST.json"
with _filename.open(encoding="ascii") as _file:
    NIST_params2 = json.load(_file)
NIST: dict[str, Curve] = {
    _ec_name: _catalogued_curve(NIST_params2[_ec_name], _ec_name)
    for _ec_name in NIST_params2
}
# SEC 2 v.1 curves, removed from SEC 2 v.2 as insecure ones
# http://www.secg.org/SEC2-Ver-1.0.pdf
_filename = datadir / "ec_SEC2v1_insecure.json"
with _filename.open(encoding="ascii") as _file:
    SEC2v1_params2 = json.load(_file)
SEC2v1: dict[str, Curve] = {
    _ec_name: _catalogued_curve(SEC2v1_params2[_ec_name], _ec_name)
    for _ec_name in SEC2v1_params2
}
# curves included in both SEC 2 v.1 and SEC 2 v.2
# http://www.secg.org/sec2-v2.pdf
_filename = datadir / "ec_SEC2v2.json"
with _filename.open(encoding="ascii") as _file:
    SEC2v2_params2 = json.load(_file)
SEC2v2: dict[str, Curve] = {}
for _ec_name in SEC2v2_params2:
    # one object in both catalogues, not two: building the curve twice
    # would hand out two objects, and only one of them the secp256k1 the
    # libsecp256k1 dispatch below compares against
    SEC2v2[_ec_name] = _catalogued_curve(SEC2v2_params2[_ec_name], _ec_name)
    SEC2v1[_ec_name] = SEC2v2[_ec_name]

# a new dict, deliberately: aliasing (CURVES = SEC2v1) followed by
# update() calls would pour NIST and Brainpool into the SEC 2 v.1
# catalogue -- SEC2v1 with 27 entries instead of its own 15, and
# SEC2v1["nistp256"] answering a curve that is not in SEC 2 v.1 at all.
# Each catalogue holds what it is named after
CURVES = SEC2v1 | NIST | Brainpool

secp256k1 = CURVES["secp256k1"]


def _libsecp256k1_applicable(ec: Curve, hf: HashF | None) -> bool:
    """Return True if the libsecp256k1 bindings can serve ec and hf.

    Every dispatch to the bindings asks here, so that the predicates
    cannot drift apart the way hand-written copies would; a caller
    with a further condition of its own -- mult, whose bindings take the
    generator and a non-zero scalar alone -- ands it on top.

    hf is compared by identity, deliberately: nothing short of running
    the two functions tells sha256 from a look-alike, so a wrapper such
    as functools.partial(sha256) falls back to the Python path. That is
    the conservative direction -- slower, never wrong.
    """
    if ec != secp256k1:
        return False
    return hf is None or hf is sha256


def _compressed_sec(x: int, ec: Curve) -> bytes | None:
    """Return 0x02 || x for the bindings to parse, None if they cannot.

    The two functions below ask libsecp256k1 the one question a compressed
    public key is -- "this x, and the y that goes with it" -- and this is
    the argument they ask it with, plus the conditions under which there
    is one: the curve has to be secp256k1, and x has to be a field
    element, ec_pubkey_parse taking no x-coordinate at or above ec.p and
    x.to_bytes raising OverflowError rather than answering for one.
    """
    if not _libsecp256k1_applicable(ec, None) or not 0 <= x < ec.p:
        return None
    return b"\x02" + x.to_bytes(ec.p_size, "big")


def _is_x_coordinate_var(x: int, ec: Curve) -> bool:
    """Return True if x is the x-coordinate of a point of the curve.

    Existence and nothing else, which is what a caller with no use for
    the y has to ask, and it is a question the Legendre symbol answers
    without ever forming a root: 14 us on secp256k1 against the 75 of
    ec.y, and ec_pubkey_parse answers the same of the compressed key
    0x02 || x in 2.4 -- the same answer three ways, all three refusing
    the same x. It is libsecp256k1's own shape, `secp256k1_ge_x_on_curve_var`
    being `secp256k1_fe_is_square_var` of x^3 + ax + b and nothing else.

    A bool rather than an exception, because the value that names itself
    in an error message is the caller's and not this x: dsa.Sig's
    congruence check tries every x congruent to r and reports r. That is
    also what keeps the refusal cheap, where _y_even_var below cannot: half
    of the field elements are not x-coordinates, and the symbol costs the
    same for those as for the others.
    """
    sec = _compressed_sec(x, ec)
    if sec is not None:
        try:
            libsecp256k1_pubkey_parse(sec)
        except ValueError:
            return False
        return True

    if not 0 <= x < ec.p:
        return False
    # the symbol is 0 for a y^2 of zero, which is the two-torsion point:
    # its root is zero and it is on the curve, so -1 is the whole of what
    # says otherwise
    return legendre_symbol_var(ec._y2(x), ec.p) != -1


def _y_even_var(x: int, ec: Curve) -> int:
    """Return the even y-coordinate associated to x.

    ec.y_even_var, delegated for secp256k1: the parity a compressed public
    key carries in its prefix is the same tiebreaker, so 0x02 || x names
    the even-y point and the uncompressed serialization of it hands back
    the y that was lifted -- 2.9 us against 75. That is 0.5 more than
    _is_x_coordinate_var above, which is why both exist.

    An x the bindings refuse falls through to ec.y_even_var instead of
    raising here, so that the message stays in the one place that has the
    value to name: "invalid x-coordinate" is curve_group's to phrase, and
    the callers of this function wrap that message rather than restating
    it. The fallthrough pays the Python square root on a path whose
    answer is an exception, which is the trade _is_x_coordinate_var exists
    not to make.
    """
    sec = _compressed_sec(x, ec)
    if sec is not None:
        with contextlib.suppress(ValueError):
            pubkey = libsecp256k1_pubkey_parse(sec)
            uncompressed = libsecp256k1_pubkey_serialize(pubkey, compressed=False)
            return int.from_bytes(uncompressed[ec.p_size + 1 :], "big")

    return ec.y_even_var(x)


def _sec_from_point(Q: Point) -> bytes:
    """Return a point of secp256k1 as the octets the bindings parse.

    Neither on-curve nor infinity is checked here: this is the inside of
    the dispatches below, past their require_on_curve, and sec_point's
    bytes_from_point is unreachable from this module anyway -- that one
    is built on this one.

    Uncompressed, 0x04 || x || y, which is what makes the round trip
    worth taking, in both directions. It is the form ec_pubkey_parse
    reads without lifting an x coordinate back to a point, 2.1 us of the
    13 a whole multiplication costs; and, asked of ec_pubkey_serialize on
    the way out, the form that does not drop a y this side would have to
    lift again -- 3.2 us of point_from_octets against 1.2, a lift
    delegated to the bindings against two int.from_bytes, the lesson
    bip32.py records for public derivation. The 32 octets more cost
    0.09 us to write here.
    """
    p_size = secp256k1.p_size
    return b"\x04" + Q[0].to_bytes(p_size, "big") + Q[1].to_bytes(p_size, "big")


def _libsecp256k1_multi_mult_(
    scalars: Sequence[int], secs: Sequence[bytes]
) -> bytes | None:
    """Return sum(scalars[i]*points[i]) as octets, None for infinity.

    The bytes-in/bytes-out layer the gain lives on: a term is one
    ec_pubkey_tweak_mul, the running total one ec_pubkey_combine, and no
    intermediate becomes a Point -- each of those would pay a parse on
    the way out and a serialization on the way back in.

    None rather than octets, because infinity has no serialization: a
    libsecp256k1 pubkey is a point of the curve and never the identity.
    Every scalar is therefore required to be in [1, n-1] and every point
    to be a point of secp256k1 that is not infinity -- the callers below
    gate on exactly that -- which leaves the sum as the one infinity to
    answer for: u*H + v*Q with v*Q == -u*H, and v = n - u with Q == H is
    the one-line case of it.

    That sum is recognized from the coordinates, same x and different y,
    rather than caught from the combine that fails on it, so that a
    ValueError raised in here still means what it says instead of
    doubling as a value. Its price is one combine per term rather than
    one for all of them, a running total being what has an x to compare:
    measured on eight terms 112 us against 97, and on sixty-four 925
    against 774, where the Python arithmetic below takes 2.4 ms and 15 ms.
    Two terms, which is double_mult_var and the shape most callers have, pay
    nothing at all: one combine either way.
    """
    x_slice = slice(1, secp256k1.p_size + 1)
    total: bytes | None = None
    for m, sec in zip(scalars, secs, strict=True):
        term = libsecp256k1_pubkey_tweak_mul(sec, m, False)
        if total is None:  # nothing yet, or infinity, and INF + P is P
            total = term
        elif total != term and total[x_slice] == term[x_slice]:
            # same x, different y, i.e. P + (-P): infinity. Equal octets
            # instead are P + P, which combine doubles like any other sum
            total = None
        else:
            total = libsecp256k1_pubkey_combine([total, term], False)
    return total


def _libsecp256k1_multi_mult(scalars: Sequence[int], points: Sequence[Point]) -> Point:
    """Return sum(scalars[i]*points[i]), through the bindings.

    The Point signature the callers keep; the arithmetic is the bytes
    layer above, whose None is this function's INF.
    """
    sec = _libsecp256k1_multi_mult_(scalars, [_sec_from_point(Q) for Q in points])
    if sec is None:
        return INF
    p_size = secp256k1.p_size
    return (
        int.from_bytes(sec[1 : p_size + 1], "big"),
        int.from_bytes(sec[p_size + 1 :], "big"),
    )


# the widths mult and double_mult_var hand the variants below them; the
# measurement behind each is in the docstring of the function it is passed
# to, and they are two constants rather than one because what a window is
# measured on is the length of the scalars in it: the GLV endomorphism's
# halves take the first, whether one coefficient was split into two of
# them or two into four, and an interleaved wNAF's full-length
# coefficients take the second
_ENDOMORPHISM_W = 4
_DOUBLE_MULT_W = 4
# and the width the fixed-base ladder holds a table at, which is a
# third question again: its table is memoized, so what the width buys
# is paid in memory once and not in additions per call. The
# measurement is in _mult_fixed_base's docstring
_FIXED_BASE_W = 6


def mult(m_int: Integer, Q: Point | None = None, ec: Curve = secp256k1) -> Point:
    """Elliptic curve scalar multiplication."""
    m: int = int_from_integer(m_int) % ec.n

    # m == 0 is the infinity point, which the bindings reject as a scalar
    if m and _libsecp256k1_applicable(ec, None):
        # the generator is ec_pubkey_create, with no point to parse first
        if Q is None or Q == ec.G:
            return libsecp256k1_mult(m)
        ec.require_on_curve(Q)
        # any other point, infinity excepted: that one is not a pubkey,
        # and m*INF == INF is what the Python path below answers anyway
        if Q[1]:
            return _libsecp256k1_multi_mult([m], [Q])

    if Q is None or Q == ec.G:
        # the fixed-base case, and the whole of what makes it one: the
        # point is the same on every call, so its per-position tables are
        # built once and kept and the multiplication makes no doubling at
        # all. It is faster than the endomorphism below on secp256k1 too,
        # so the test is on the point before it is on the curve
        return ec.aff_from_jac_var(_mult_fixed_base(m, ec.GJ, ec, _FIXED_BASE_W))

    ec.require_on_curve(Q)
    QJ = _jac_from_aff(Q)

    # what reaches here on secp256k1 is the arguments the bindings decline
    # -- a zero scalar, or infinity -- and, with the dispatch
    # above patched off, every multiplication of the curve: that is the
    # reference implementation the test suite holds the bindings against,
    # and the GLV endomorphism is its fastest form, 0.59 ms against the
    # 0.82 of _mult, the decomposition being secp256k1's own lambda and
    # beta. Both are regular: the number of point additions either makes
    # is the same for every scalar, which is what a private key or a nonce
    # arriving here needs and what issue 254 is about -- the endomorphism
    # over interleaved wNAFs would be 0.51 ms and 51 to 64 additions.
    # Not spelled as _libsecp256k1_applicable, though it is the same
    # test today: what decides here is whether the curve has that
    # endomorphism, so patching the bindings off must leave this arm --
    # python_path_test.py's pattern, which otherwise would compare the
    # bindings against the generic double-and-add of every other curve
    # the scalar of a mult is a private key or a nonce in every caller
    # btclib has, so the point it multiplies is rescaled first: same
    # affine point, a Z nobody can predict, and intermediate values that
    # stop being a function of m alone. _blinded_jac says what that buys
    # and what it does not
    QJ = _blinded_jac(QJ, ec)

    R = (
        _mult_endomorphism_secp256k1(m, QJ, ec, _ENDOMORPHISM_W)
        if ec == secp256k1
        else _mult(m, QJ, ec)
    )
    return ec.aff_from_jac_var(R)


def _double_mult_python(
    u: int, HJ: JacPoint, v: int, QJ: JacPoint, ec: Curve
) -> JacPoint:
    """Return u*HJ + v*QJ in Python, through the endomorphism if there is one.

    The arm `double_mult_var` and `_jac_double_mult` share, so that one place
    decides which double multiplication a curve gets and both reach the
    same one. On secp256k1 that is the GLV split of both coefficients,
    which is to `_double_mult_w_NAF_var` what `_mult_endomorphism_secp256k1`
    is to `_mult`: the same answer for ~128 doublings instead of ~256.

    Dispatched on the curve having the endomorphism, not on
    `_libsecp256k1_applicable` -- the same test today, and not the same
    question. `mult` says why at length: patching the bindings off is how
    python_path_test.py holds them against the Python arithmetic, and a
    dispatch spelled the other way would answer that test with the generic
    interleaved wNAF every other curve runs instead of with secp256k1's
    own fastest path.

    Which makes this the second curve comparison of the call, the guard
    above having asked `_libsecp256k1_applicable` the first: 0.394 us on a
    curve that is not secp256k1, the frame and `Curve.__eq__`'s two
    _eq_key tuples together, where the identical object short-circuits on
    identity. That is 8% of a low-cardinality double multiplication and
    two tenths of a second of the suite, spent for the same reason
    _double_mult_w_NAF_var spends about 3 us a call there: what the saving
    would buy is a fraction of a second, and what it would cost is a
    second copy of the dispatch, one per caller, free to drift. `mult`
    makes the same two comparisons for the same reason.
    """
    if ec == secp256k1:
        return _double_mult_endomorphism_secp256k1_var(
            u, HJ, v, QJ, ec, _ENDOMORPHISM_W
        )
    return _double_mult_w_NAF_var(u, HJ, v, QJ, ec, _DOUBLE_MULT_W)


def double_mult_var(
    u: Integer, H: Point, v: Integer, Q: Point, ec: Curve = secp256k1
) -> Point:
    """Double scalar multiplication (u*H + v*Q)."""
    ec.require_on_curve(H)
    ec.require_on_curve(Q)

    u = int_from_integer(u) % ec.n
    v = int_from_integer(v) % ec.n

    # a zero scalar and infinity are what the bindings decline, and the
    # term they make is nothing: dropping it here would leave the empty
    # sum -- infinity -- to answer for as well, which the Python path
    # below answers already, so the whole call goes there instead
    if u and v and H[1] and Q[1] and _libsecp256k1_applicable(ec, None):
        return _libsecp256k1_multi_mult([u, v], [H, Q])

    HJ = _jac_from_aff(H)
    QJ = _jac_from_aff(Q)
    R = _double_mult_python(u, HJ, v, QJ, ec)
    return ec.aff_from_jac_var(R)


def _jac_double_mult(u: int, HJ: JacPoint, v: int, QJ: JacPoint, ec: Curve) -> JacPoint:
    """Return u*HJ + v*QJ in Jacobian coordinates, delegated where it can be.

    double_mult_var for a caller whose equation is written in projective
    coordinates: dsa's and ssa's _assert_as_valid_, which are the two
    verifications the bindings' own decline -- a hash function that is not
    sha256, a BIP340 message that is not 32 bytes (issue 169), a
    caller-imposed nonce, another curve -- and which paid a Python
    double_mult_var underneath whatever the reason. 1.02 ms against 28 us on
    secp256k1.

    Jacobian in and Jacobian out, rather than those two rewritten in
    affine coordinates, because it is not only their arithmetic that is
    projective: so are the infinity test, the y parity and the x
    comparison each makes, and so is the QJ that public key recovery
    threads through dsa's. _jac_from_aff is what keeps that exact --
    infinity has no serialization on the other side of the boundary, and
    it answers the z == 0 both functions already recognize, so each still
    raises what it raised before, from the same line.

    The two conversions in are one modular inversion each on the z == 1
    that a parsed key and a lifted r arrive as, and a shortcut for that
    case -- the affine point being the same pair of coordinates, no
    inversion at all -- saves both of them, 3% of the 28 us the call
    costs. Not worth a branch, and neither is the caller's own
    mod_inv_var(1) on the way back out, the same inversion again on the
    cheapest operand it has.
    """
    if not _libsecp256k1_applicable(ec, None):
        return _double_mult_python(u, HJ, v, QJ, ec)

    R = double_mult_var(u, ec.aff_from_jac_var(HJ), v, ec.aff_from_jac_var(QJ), ec)
    return _jac_from_aff(R)


def multi_mult_var(
    scalars: Sequence[Integer], points: Sequence[Point], ec: Curve = secp256k1
) -> Point:
    """Return the multi scalar multiplication u1*Q1 + ... + un*Qn.

    Interleaved wNAF on few scalars, Bos-Coster on many: curve_group's
    _multi_mult_var dispatches on the count, at the size the two measure the
    same. On secp256k1 the bindings serve the whole sum instead, and this
    is the one caller that hands them many scalars at once -- libsecp256k1
    exposing no batch verification, ssa's is built on this.
    """
    if len(scalars) != len(points):
        err_msg = "mismatch between number of scalars and points: "
        err_msg += f"{len(scalars)} vs {len(points)}"
        raise BTClibValueError(err_msg)

    ints = [int_from_integer(s) % ec.n for s in scalars]
    for Q in points:
        ec.require_on_curve(Q)

    # as in double_mult_var; and fewer than two terms is not a multi_mult_var at
    # all, an error the Python path below is the one to raise
    if (
        len(points) > 1
        and _libsecp256k1_applicable(ec, None)
        and all(m and Q[1] for m, Q in zip(ints, points, strict=True))
    ):
        return _libsecp256k1_multi_mult(ints, points)

    jac_points = [_jac_from_aff(Q) for Q in points]
    R = _multi_mult_var(ints, jac_points, ec)
    return ec.aff_from_jac_var(R)
