# Skip execution of one or more hooks using the SKIP environment variable:
# $ SKIP=pylint git commit -m "foo"
# $ SKIP=mypy,pylint pre-commit run --all-files
#
# If want to disable all hooks while committing, use the --no-verify/-n option:
# $ git commit -n -m "foo"

# Since pylint and mypy need to import modules and dependencies to work correctly,
# their hooks only work with a local installation (in your environment).
# see https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-case-conflict
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable
      # - id: fix-byte-order-marker
      # - id: fix-encoding-pragma
      - id: check-yaml
      - id: check-json
      # - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-docstring-first
      # - id: name-tests-test
      - id: check-toml
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.6.0
    hooks:
      - id: markdownlint-cli2-fix
        name: markdownlint-cli2-fix (in place fixes)
  - repo: https://github.com/leoll2/copyright_notice_precommit
    rev: 0.1.1
    hooks:
      - id: copyright-notice
        args: [--notice=COPYRIGHT]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --expand-star-imports
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --remove-rhs-for-unused-variables
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        # exclude: *fixtures
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: isort (black profile, in place fixes)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        #exclude: *fixtures
        #args: ["--max-summary-lines=2", "--linewrap-full-docstring"]
        files: "python"
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: black (in place fixes)
        # args: [--diff, --check]
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        # language_version: python3.11
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit (btclib)
        args: []
        exclude: test_*
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit (tests)
        # disable B101 (Test for use of assert) on tests folder
        args: ["-s", "B101"]
        exclude: btclib
  - repo: local
    hooks:
      - id: pylint
        name: pylint (local)
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy (local)
        entry: mypy
        language: python
        types: [python]
        args: []
        #require_serial: true
        #additional_dependencies:
        #  [
        #    "isort>=5",
        #    "platformdirs==2.2.0",
        #    "py==1.11",
        #    "tomlkit>=0.10.1",
        #    "types-pkg_resources==0.1.3",
        #  ]
        #exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        description: Check the completeness of MANIFEST.in for Python packages.
        language: python
        pass_filenames: false
        always_run: true
  - repo: https://github.com/regebro/pyroma
    rev: "4.1"
    hooks:
      - id: pyroma
