#!/usr/bin/env python3

# Copyright (C) The btclib developers
#
# This file is part of btclib. It is subject to the license terms in the
# LICENSE file found in the top-level directory of this distribution.
#
# No part of btclib including this file, may be copied, modified, propagated,
# or distributed except according to the terms contained in the LICENSE file.
"""Tests for the `btclib.script.engine` module.

Three vendored files, none of them from a BIP, and all three under the
name their upstream gives them: `script_assets_test.json` lives in
`unit_test_data/` of bitcoin-core/qa-assets, a dump generated by Core's
`test/functional/feature_taproot.py --dumptests`, while `tx_valid.json`
and `tx_invalid.json` are Core's own files, entire.
tests/_data/README.md pins the revision of each.
"""

from typing import Any

import pytest

from btclib.exceptions import BTClibValueError
from btclib.script import ScriptPubKey
from btclib.script.engine import (
    ALL_FLAGS,
    NO_FLAGS,
    ScriptFlag,
    ScriptFlags,
    verify_amounts,
    verify_input,
    verify_transaction,
)
from btclib.script.witness import Witness
from btclib.tx import OutPoint, Tx, TxIn
from btclib.tx.tx_out import TxOut
from tests import vectors
from tests.script_engine import parse_script

TAPSCRIPT = vectors.load("script", "_data", "script_assets_test.json")


def taproot_vectors(outcome: str) -> list[Any]:
    """Every vector carrying an `outcome` witness, whatever its flags.

    `"TAPROOT" in x["flags"]` used to stand here as well, and it dropped
    1016 of the file's 3737 cases: 685 `success` and 331 `failure` whose
    flags field stops at NULLDUMMY. Those are not off-topic vectors.
    Core's `feature_taproot.py` dumps a spend twice, once with the soft
    fork enforced and once without, and the second copy is what asserts
    that a taproot output stays anyone-can-spend to a node that does not
    know the rule -- the upgrade path, which the filter left untested
    while testing the rule itself 2721 times.

    Nothing was hidden behind it: all 1016 pass as they stand, 685
    accepted and 331 refused, so this is a coverage change and not a fix.
    Nor were they covered elsewhere -- 612 of them are reached by no other
    test, and the remaining 73 only by `test_valid_script_path`, which
    checks the taproot commitment and runs no script.

    """
    return [
        pytest.param(x, id=vectors.vector_id(index, x["comment"]))
        for index, x in enumerate(TAPSCRIPT)
        if outcome in x
    ]


@pytest.mark.parametrize("vector", taproot_vectors("success"))
def test_valid_taproot(vector: dict[str, Any]) -> None:
    tx = Tx.parse(vector["tx"])

    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    witness = Witness(vector["success"]["witness"])
    tx.vin[index].script_witness = witness
    tx.vin[index].script_sig = bytes.fromhex(vector["success"]["scriptSig"])

    flags = vector["flags"].split(",")

    verify_input(prevouts, tx, index, flags)


@pytest.mark.parametrize("vector", taproot_vectors("failure"))
def test_invalid_taproot(vector: dict[str, Any]) -> None:
    tx = Tx.parse(vector["tx"])

    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    witness = Witness(vector["failure"]["witness"])
    tx.vin[index].script_witness = witness
    tx.vin[index].script_sig = bytes.fromhex(vector["failure"]["scriptSig"])

    flags = vector["flags"].split(",")
    with pytest.raises((BTClibValueError, IndexError, KeyError)):
        verify_input(prevouts, tx, index, flags)


def annex_vectors() -> list[Any]:
    """The TAPROOT vectors whose witness carries an annex to be stripped.

    The flags test `taproot_vectors` above no longer makes is kept here,
    and selects the same 248 vectors with or without it: no vector whose
    flags stop short of TAPROOT carries an annex, measured. It stays as
    the statement that an annex is a taproot notion, which is what makes
    a future vector contradicting it worth looking at.
    """
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if "TAPROOT" not in x["flags"]:
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) < 2 or stack[-1][0] != 0x50:
            continue
        params.append(pytest.param(x, id=vectors.vector_id(index, x["comment"])))
    return params


ANNEX_VECTORS = annex_vectors()


def test_annex_vectors_exist() -> None:
    """`test_verify_input_does_not_touch_the_tx` needs an annex to strip.

    It was the `assert annexed` at the end of the loop; a parametrized
    test over no parameter is one green skip, so the count is asserted
    here rather than not at all.
    """
    assert ANNEX_VECTORS


@pytest.mark.parametrize("vector", ANNEX_VECTORS)
def test_verify_input_does_not_touch_the_tx(vector: dict[str, Any]) -> None:
    """Verifying an input must leave the witness of the caller's Tx alone.

    `taproot_get_annex` used to assign the trimmed stack back to the witness,
    and the segwit v0 branches handed the interpreter the witness stack itself,
    which pops what it consumes: `verify_transaction` rewrote the very Tx it
    was validating (issue #140).
    """
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    stack = Witness(vector["success"]["witness"]).stack

    tx = Tx.parse(vector["tx"])
    tx.vin[index].script_witness = Witness(stack)
    tx.vin[index].script_sig = bytes.fromhex(vector["success"]["scriptSig"])
    serialized = tx.serialize(include_witness=True, check_validity=False)

    verify_input(prevouts, tx, index, vector["flags"].split(","))

    assert tx.vin[index].script_witness.stack == stack
    assert tx.serialize(include_witness=True, check_validity=False) == serialized


def legacy_vectors(fname: str) -> list[Any]:
    """Every vector of a Bitcoin Core tx_valid/tx_invalid.json, comments aside.

    The files keep Core's names because they are Core's files entire: the
    `_legacy` they used to carry read as a subsetting that never happened
    -- 121 valid and 93 invalid vectors here, 121 and 93 upstream -- and
    the content is not legacy either, 2 valid and 14 invalid vectors
    naming WITNESS in their flags (issue 168). The `legacy` of the test
    names below is another matter and stays: it distinguishes the pre-
    taproot validation path these vectors drive from the BIP341 ones
    above, and issue 129 cites `test_invalid_legacy` by name.

    Nothing is filtered here any more. The loop this replaces skipped
    whatever `Tx.parse` refused -- 2 of the then 119 valid vectors and 8
    of the 93 invalid ones -- and the two it dropped from the valid file
    were a genuine refusal it was hiding: btclib bounded an amount by the
    issued supply rather than by MAX_MONEY, and could not parse the two
    `MAX_MONEY output` transactions (issue 167). A valid vector btclib
    cannot parse must fail, and an invalid one refused at parse time is
    refused, which is all its test asks.
    """
    params = []
    comment = ""
    for index, x in enumerate(vectors.load("script_engine", "_data", fname)):
        if isinstance(x[0], str):
            # a comment line, and it describes the vectors that follow:
            # "MAX_MONEY output", "Coinbase of size 2". The flags field
            # was the id before, which named a dozen vectors "41-P2SH"
            comment = x[0]
            continue
        params.append(pytest.param(x, id=vectors.vector_id(index, comment, x[2])))
    return params


def prevouts_of(vector: list[Any]) -> tuple[list[TxOut], bool]:
    """The spent outputs of a legacy vector, and whether they carry amounts."""
    check_amounts = True
    prevouts = []
    for i in vector[0]:
        amount = 0 if len(i) == 3 else i[3]
        if not amount:
            check_amounts = False
        prevouts.append(TxOut(amount, ScriptPubKey(parse_script(i[2]))))
    return prevouts, check_amounts


def witness_v0_vectors() -> list[Any]:
    """The valid legacy vectors that spend a witness v0 output.

    The two further `continue` of the loop: a tx with no witness has none
    to leave alone, and one whose input count does not match the prevouts
    the vector lists cannot be verified at all.
    """
    params = []
    for param in legacy_vectors("tx_valid.json"):
        x = param.values[0]
        tx = Tx.parse(x[1])
        if not any(vin.script_witness.stack for vin in tx.vin):
            continue
        # no vector in today's tx_valid.json lists prevouts that do not
        # match its inputs: this guard waits for the upstream refresh
        # that brings one, and a synthetic vector written to cover it
        # would test the vendored data, not btclib
        if len(x[0]) != len(tx.vin):
            continue  # pragma: no cover
        params.append(param)
    return params


WITNESS_V0_VECTORS = witness_v0_vectors()


def test_witness_v0_vectors_exist() -> None:
    """The test below proves nothing without a witness to leave alone."""
    assert WITNESS_V0_VECTORS


@pytest.mark.parametrize("vector", WITNESS_V0_VECTORS)
def test_verify_transaction_does_not_touch_witness_v0(vector: list[Any]) -> None:
    """The same, for the p2wpkh and p2wsh branches of verify_input."""
    tx = Tx.parse(vector[1])

    flags = ALL_FLAGS
    for f in vector[2].split(","):
        # unreached with today's data: the witness-v0 vectors name
        # NONE, LOW_S and DISCOURAGE_UPGRADABLE_WITNESS_PROGRAM, and
        # neither of the last two is in ALL_FLAGS. The removal starts
        # running the day one of them is enforced there, or a vector
        # shows up carrying a flag the engine does enforce.
        # NONE is not a member of the enum, hence the first test: it is
        # how Core spells an empty flag field, not a rule to switch off
        if f in ScriptFlag.__members__ and ScriptFlag[f] in flags:
            flags &= ~ScriptFlag[f]  # pragma: no cover

    prevouts, check_amounts = prevouts_of(vector)

    stacks = [vin.script_witness.stack[:] for vin in tx.vin]
    serialized = tx.serialize(include_witness=True, check_validity=False)

    # flags, not `flags or None`: a ScriptFlag with nothing left in it is
    # falsy, and the day the loop above empties it that would have asked
    # for the default set instead of for no rule at all
    verify_transaction(prevouts, tx, flags, check_amounts)

    assert [vin.script_witness.stack for vin in tx.vin] == stacks
    assert tx.serialize(include_witness=True, check_validity=False) == serialized


# every rule but the four Core classifies as policy alone: a vector
# switching one off names it in its own flags field, and the test takes it
# out of this set. Spelled out rather than written as the complement of the
# four, so that a member added to ScriptFlag does not silently join it.
# The four were commented-out strings here too, "MINMALIF" among them --
# misspelled, hence unenablable, which is the typo issue #145 is about
CONSENSUS_FLAGS = (
    ScriptFlag.P2SH
    | ScriptFlag.SIGPUSHONLY
    | ScriptFlag.LOW_S
    | ScriptFlag.STRICTENC
    | ScriptFlag.DERSIG
    | ScriptFlag.CONST_SCRIPTCODE
    | ScriptFlag.NULLDUMMY
    | ScriptFlag.CLEANSTACK
    | ScriptFlag.MINIMALDATA
    | ScriptFlag.CHECKLOCKTIMEVERIFY
    | ScriptFlag.CHECKSEQUENCEVERIFY
    | ScriptFlag.WITNESS
    | ScriptFlag.WITNESS_PUBKEYTYPE
    | ScriptFlag.TAPROOT
)


def flags_of(vector: list[Any]) -> ScriptFlags:
    """The flags field of a legacy vector, as verify_transaction takes it.

    The field is Core's comma-separated one and needs no splitting here:
    an empty field and its `"NONE"` spelling are both no rule at all.
    `"BADTX"` is not a flag and is not treated as one -- it is Core's
    marker for the nine tx_invalid vectors that must fail CheckTransaction
    before a script runs, so those are verified with no rule enabled,
    which is what naming no flag the engine knows did before.
    """
    return NO_FLAGS if vector[2] == "BADTX" else str(vector[2])


@pytest.mark.parametrize("vector", legacy_vectors("tx_valid.json"))
def test_valid_legacy(vector: list[Any]) -> None:
    tx = Tx.parse(vector[1])

    flags = CONSENSUS_FLAGS
    for f in vector[2].split(","):
        # `f in ScriptFlag.__members__` is the test the `f in flags` of a
        # list of strings was: NONE, and no other name in the two files, is
        # not a member
        if f in ScriptFlag.__members__:
            flags &= ~ScriptFlag[f]

    prevouts, check_amounts = prevouts_of(vector)

    verify_transaction(prevouts, tx, flags, check_amounts)


@pytest.mark.parametrize("vector", legacy_vectors("tx_invalid.json"))
def test_invalid_legacy(vector: list[Any]) -> None:
    prevouts, check_amounts = prevouts_of(vector)

    # Tx.parse inside the raises block, not before it: 8 of these
    # transactions are malformed enough that btclib refuses them there,
    # and refusing them there is refusing them. The loop parsed first and
    # skipped what raised, so those 8 asserted nothing at all
    with pytest.raises((BTClibValueError, IndexError, KeyError)):
        tx = Tx.parse(vector[1])
        # the vector's own flags, and only those: an invalid transaction
        # must be refused by the rules its vector names. A "NONE" field
        # used to be turned into the default set, i.e. into more rules than
        # the vector asks for, which is the wrong direction for a vector
        # that has to fail
        verify_transaction(prevouts, tx, flags_of(vector), check_amounts)


def test_invalid_amount() -> None:
    prevout = TxOut(0, ScriptPubKey(""))

    tx = Tx(vin=[TxIn(OutPoint(b"1" * 32, 1))], vout=[TxOut(10, ScriptPubKey(""))])

    # Output amount greater than sum of inputs
    with pytest.raises(BTClibValueError):
        verify_amounts([prevout], tx)
