# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""Tests for the `btclib.script.engine` module.

Three vendored files, none of them from a BIP, and all three under the
name their upstream gives them: `script_assets_test.json` lives in
`unit_test_data/` of bitcoin-core/qa-assets, a dump generated by Core's
`test/functional/feature_taproot.py --dumptests`, while `tx_valid.json`
and `tx_invalid.json` are Core's own files, entire.
tests/_data/README.md pins the revision of each.
"""

from typing import Any

import pytest

from btclib.exceptions import BTClibValueError
from btclib.script import ScriptPubKey
from btclib.script.engine import (
    ALL_FLAGS,
    NO_FLAGS,
    ScriptFlag,
    ScriptFlags,
    verify_amounts,
    verify_input,
    verify_transaction,
)
from btclib.script.witness import Witness
from btclib.tx import OutPoint, Tx, TxIn
from btclib.tx.tx_out import TxOut
from tests import load, vector_id
from tests.script_engine import parse_script

TAPSCRIPT = load("script", "_data", "script_assets_test.json")


def taproot_vectors(outcome: str) -> list[Any]:
    """Every vector carrying an `outcome` witness, whatever its flags.

    No `"TAPROOT" in x["flags"]` filter: it would drop 1016 of the
    file's 3737 cases, 685 `success` and 331 `failure` whose flags field
    stops at NULLDUMMY, and those are not off-topic vectors. Core's
    `feature_taproot.py` dumps a spend twice, once with the soft fork
    enforced and once without, and the second copy is what asserts that
    a taproot output stays anyone-can-spend to a node that does not
    know the rule -- the upgrade path. Nothing else covers them: 612 of
    them are reached by no other test, and the remaining 73 only by
    `test_valid_script_path`, which checks the taproot commitment and
    runs no script.
    """
    return [
        pytest.param(x, id=vector_id(index, x["comment"]))
        for index, x in enumerate(TAPSCRIPT)
        if outcome in x
    ]


@pytest.mark.parametrize("vector", taproot_vectors("success"))
def test_valid_taproot(vector: dict[str, Any]) -> None:
    """Reproduce the success branch of Core's script_assets_test.json."""
    tx = Tx.parse(vector["tx"])

    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    witness = Witness(vector["success"]["witness"])
    tx.vin[index].script_witness = witness
    tx.vin[index].script_sig = bytes.fromhex(vector["success"]["scriptSig"])

    flags = vector["flags"].split(",")

    verify_input(prevouts, tx, index, flags)


@pytest.mark.parametrize("vector", taproot_vectors("failure"))
def test_invalid_taproot(vector: dict[str, Any]) -> None:
    """Reproduce the failure branch of Core's script_assets_test.json."""
    tx = Tx.parse(vector["tx"])

    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    witness = Witness(vector["failure"]["witness"])
    tx.vin[index].script_witness = witness
    tx.vin[index].script_sig = bytes.fromhex(vector["failure"]["scriptSig"])

    flags = vector["flags"].split(",")
    # BTClibValueError alone, as in `test_script` and for the same
    # reason: everything the engine refuses is one, ScriptError
    # included, so a bare IndexError or KeyError is the library breaking
    # the contract btclib/exceptions.py documents and not a refusal. A
    # tuple naming them as well would count a crash as the refusal it is
    # asking for: two `spendpath/truncshortcontrol` vectors once left
    # through `witness.stack[-1][0]` on an empty element
    with pytest.raises(BTClibValueError):
        verify_input(prevouts, tx, index, flags)


def annex_vectors() -> list[Any]:
    """Select the TAPROOT vectors whose witness carries an annex to strip.

    The flags test `taproot_vectors` above omits is made here, and
    selects the same 248 vectors with or without it: no vector whose
    flags stop short of TAPROOT carries an annex, measured. It stands as
    the statement that an annex is a taproot notion, which is what makes
    a future vector contradicting it worth looking at.
    """
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if "TAPROOT" not in x["flags"]:
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) < 2 or stack[-1][0] != 0x50:
            continue
        params.append(pytest.param(x, id=vector_id(index, x["comment"])))
    return params


ANNEX_VECTORS = annex_vectors()


def test_annex_vectors_exist() -> None:
    """`test_verify_input_does_not_touch_the_tx` needs an annex to strip.

    A parametrized test over no parameter is one green skip, so the
    count is asserted here rather than not at all.
    """
    assert ANNEX_VECTORS


@pytest.mark.parametrize("vector", ANNEX_VECTORS)
def test_verify_input_does_not_touch_the_tx(vector: dict[str, Any]) -> None:
    """Verifying an input must leave the witness of the caller's Tx alone.

    Guards against `taproot_get_annex` assigning the trimmed stack back
    to the witness, and against the segwit v0 branches handing the
    interpreter the witness stack itself, which pops what it consumes:
    either way `verify_transaction` rewrites the very Tx it is
    validating (issue #140).
    """
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    stack = Witness(vector["success"]["witness"]).stack

    tx = Tx.parse(vector["tx"])
    tx.vin[index].script_witness = Witness(stack)
    tx.vin[index].script_sig = bytes.fromhex(vector["success"]["scriptSig"])
    serialized = tx.serialize(include_witness=True, check_validity=False)

    verify_input(prevouts, tx, index, vector["flags"].split(","))

    assert tx.vin[index].script_witness.stack == stack
    assert tx.serialize(include_witness=True, check_validity=False) == serialized


def legacy_vectors(fname: str) -> list[Any]:
    """Every vector of a Bitcoin Core tx_valid/tx_invalid.json, comments aside.

    The files keep Core's names because they are Core's files entire --
    121 valid and 93 invalid vectors here, 121 and 93 upstream -- so a
    `_legacy` in the file names would read as a subsetting that never
    happens; nor is the content legacy, 2 valid and 14 invalid vectors
    naming WITNESS in their flags (issue 168). The `legacy` of the test
    names below is another matter and stays: it distinguishes the pre-
    taproot validation path these vectors drive from the BIP341 ones
    above, and issue 129 cites `test_invalid_legacy` by name.

    Nothing is filtered here: skipping whatever `Tx.parse` refuses hides
    genuine failures. It hid btclib bounding an amount by the issued
    supply rather than by MAX_MONEY, which made the two `MAX_MONEY
    output` transactions of the valid file unparsable (issue 167). A
    valid vector btclib cannot parse must fail, and an invalid one
    refused at parse time is refused, which is all its test asks.
    """
    params = []
    comment = ""
    for index, x in enumerate(load("script_engine", "_data", fname)):
        if isinstance(x[0], str):
            # a comment line, and it describes the vectors that follow:
            # "MAX_MONEY output", "Coinbase of size 2" -- an id the
            # flags field cannot give, naming a dozen vectors "41-P2SH"
            comment = x[0]
            continue
        params.append(pytest.param(x, id=vector_id(index, comment, x[2])))
    return params


def prevouts_of(vector: list[Any]) -> tuple[list[TxOut], bool]:
    """Return a legacy vector's prevouts and whether they carry amounts."""
    check_amounts = True
    prevouts = []
    for i in vector[0]:
        amount = 0 if len(i) == 3 else i[3]
        if not amount:
            check_amounts = False
        prevouts.append(TxOut(amount, ScriptPubKey(parse_script(i[2]))))
    return prevouts, check_amounts


def witness_v0_vectors() -> list[Any]:
    """Select the valid legacy vectors that spend a witness v0 output.

    The two further `continue` of the loop: a tx with no witness has none
    to leave alone, and one whose input count does not match the prevouts
    the vector lists cannot be verified at all.
    """
    params = []
    for param in legacy_vectors("tx_valid.json"):
        x = param.values[0]
        tx = Tx.parse(x[1])
        if not any(vin.script_witness.stack for vin in tx.vin):
            continue
        # no vector in today's tx_valid.json lists prevouts that do not
        # match its inputs: this guard waits for the upstream refresh
        # that brings one, and a synthetic vector written to cover it
        # would test the vendored data, not btclib
        if len(x[0]) != len(tx.vin):
            continue  # pragma: no cover
        params.append(param)
    return params


WITNESS_V0_VECTORS = witness_v0_vectors()


def test_witness_v0_vectors_exist() -> None:
    """The test below proves nothing without a witness to leave alone."""
    assert WITNESS_V0_VECTORS


@pytest.mark.parametrize("vector", WITNESS_V0_VECTORS)
def test_verify_transaction_does_not_touch_witness_v0(vector: list[Any]) -> None:
    """The same, for the p2wpkh and p2wsh branches of verify_input."""
    tx = Tx.parse(vector[1])

    flags = ALL_FLAGS
    for f in vector[2].split(","):
        # unreached with today's data: the witness-v0 vectors name
        # NONE, LOW_S and DISCOURAGE_UPGRADABLE_WITNESS_PROGRAM, and
        # neither of the last two is in ALL_FLAGS. The removal starts
        # running the day one of them is enforced there, or a vector
        # shows up carrying a flag the engine does enforce.
        # NONE is not a member of the enum, hence the first test: it is
        # how Core spells an empty flag field, not a rule to switch off
        if f in ScriptFlag.__members__ and ScriptFlag[f] in flags:
            flags &= ~ScriptFlag[f]  # pragma: no cover

    prevouts, check_amounts = prevouts_of(vector)

    stacks = [vin.script_witness.stack[:] for vin in tx.vin]
    serialized = tx.serialize(include_witness=True, check_validity=False)

    # flags, not `flags or None`: a ScriptFlag with nothing left in it is
    # falsy, and the day the loop above empties it that would have asked
    # for the default set instead of for no rule at all
    verify_transaction(prevouts, tx, flags, check_amounts)

    assert [vin.script_witness.stack for vin in tx.vin] == stacks
    assert tx.serialize(include_witness=True, check_validity=False) == serialized


# every rule but the four Core classifies as policy alone: a vector
# switching one off names it in its own flags field, and the test takes it
# out of this set. Spelled out rather than written as the complement of the
# four, so that a member added to ScriptFlag does not silently join it.
CONSENSUS_FLAGS = (
    ScriptFlag.P2SH
    | ScriptFlag.SIGPUSHONLY
    | ScriptFlag.LOW_S
    | ScriptFlag.STRICTENC
    | ScriptFlag.DERSIG
    | ScriptFlag.CONST_SCRIPTCODE
    | ScriptFlag.NULLDUMMY
    | ScriptFlag.CLEANSTACK
    | ScriptFlag.MINIMALDATA
    | ScriptFlag.CHECKLOCKTIMEVERIFY
    | ScriptFlag.CHECKSEQUENCEVERIFY
    | ScriptFlag.WITNESS
    | ScriptFlag.WITNESS_PUBKEYTYPE
    | ScriptFlag.TAPROOT
)


def flags_of(vector: list[Any]) -> ScriptFlags:
    """Return a legacy vector's flags field, as verify_transaction takes it.

    The field is Core's comma-separated one and needs no splitting here:
    an empty field and its `"NONE"` spelling are both no rule at all.
    `"BADTX"` is not a flag and is not treated as one -- it is Core's
    marker for the nine tx_invalid vectors that must fail CheckTransaction
    before a script runs, so those are verified with no rule enabled.
    """
    return NO_FLAGS if vector[2] == "BADTX" else str(vector[2])


@pytest.mark.parametrize("vector", legacy_vectors("tx_valid.json"))
def test_valid_legacy(vector: list[Any]) -> None:
    """Reproduce Core's tx_valid.json."""
    tx = Tx.parse(vector[1])

    flags = CONSENSUS_FLAGS
    for f in vector[2].split(","):
        # NONE, and no other name in the two files, is not a member: it
        # is Core's spelling of an empty flags field, not a rule to
        # switch off
        if f in ScriptFlag.__members__:
            flags &= ~ScriptFlag[f]

    prevouts, check_amounts = prevouts_of(vector)

    verify_transaction(prevouts, tx, flags, check_amounts)


@pytest.mark.parametrize("vector", legacy_vectors("tx_invalid.json"))
def test_invalid_legacy(vector: list[Any]) -> None:
    """Reproduce Core's tx_invalid.json."""
    prevouts, check_amounts = prevouts_of(vector)

    # Tx.parse inside the raises block, not before it: some of these
    # transactions are refused there -- malformed, or invalid as a lone
    # transaction, which is what Core's own BADTX marker says of the
    # duplicate-input vector -- and refusing them there is refusing them;
    # parsed first and skipped on failure, those would assert nothing at
    # all. BTClibValueError alone, as above: every vector leaves through
    # one, measured, so naming IndexError and KeyError too is width that
    # buys nothing and would hide the next contract break
    with pytest.raises(BTClibValueError):
        tx = Tx.parse(vector[1])
        # the vector's own flags, and only those: an invalid transaction
        # must be refused by the rules its vector names. Turning a "NONE"
        # field into the default set would enable more rules than the
        # vector asks for, the wrong direction for a vector that has to
        # fail
        verify_transaction(prevouts, tx, flags_of(vector), check_amounts)


def test_invalid_amount() -> None:
    """Refuse outputs summing to more than the inputs provide."""
    prevout = TxOut(0, ScriptPubKey(""))

    tx = Tx(vin=[TxIn(OutPoint(b"1" * 32, 1))], vout=[TxOut(10, ScriptPubKey(""))])

    # Output amount greater than sum of inputs
    with pytest.raises(BTClibValueError):
        verify_amounts([prevout], tx)


def test_a_prevout_per_input() -> None:
    """Verify each input against its own prevout: one list each, one length.

    The caller brings the prevouts, an outpoint saying neither what it is
    worth nor what it locks, so nothing but this check says they are the
    prevouts of *this* transaction: one short and the loop below would
    verify the inputs it has against the wrong outputs, or fall off the
    list.
    """
    prevout = TxOut(10, ScriptPubKey(""))
    tx = Tx(
        vin=[TxIn(OutPoint(b"1" * 32, 1)), TxIn(OutPoint(b"1" * 32, 2))],
        vout=[TxOut(10, ScriptPubKey(""))],
    )

    with pytest.raises(BTClibValueError, match="1 prevouts for 2 transaction inputs"):
        verify_transaction([prevout], tx)
