# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""Tests for the `btclib.sig_hash` module.

Two vendored files, from two upstreams:

- `taproot_test_vector.json` is bip-0341's `wallet-test-vectors.json`,
  https://github.com/bitcoin/bips/blob/master/bip-0341/wallet-test-vectors.json
- `script_assets_test.json` is *not* in a BIP. It is
  `unit_test_data/script_assets_test.json` of bitcoin-core/qa-assets --
  upstream's own name, kept -- generated by Core's
  `test/functional/feature_taproot.py --dumptests`, which is why bip-0341
  does not lead to it.

tests/_data/README.md pins the revision of each.
"""

from typing import Any

import pytest

from btclib.alias import Octets, ScriptList, TaprootScriptTree
from btclib.ecc import ssa
from btclib.exceptions import (
    BTClibRuntimeError,
    BTClibTypeError,
    BTClibValueError,
)
from btclib.hashes import hash160, sha256
from btclib.script import (
    ScriptPubKey,
    Witness,
    input_script_sig,
    is_p2tr,
    output_prvkey,
    parse,
    serialize,
    sig_hash,
    type_and_payload,
)
from btclib.script.engine import verify_transaction
from btclib.script.taproot import serialize as taproot_serialize
from btclib.to_pub_key import pub_keyinfo_from_prv_key
from btclib.tx import OutPoint, Tx, TxIn, TxOut
from tests import load, vector_id

# what a refused BIP340 signature says, on either arm: libsecp256k1
# answers a boolean and btclib supplies the sentence, while the Python
# arm names the check that failed. Issue #998 is whether the two should
# agree; until it is decided, both are asserted rather than neither
_REFUSED = "signature verification failed|y_K is odd"

TAPSCRIPT = load("script", "_data", "script_assets_test.json")


def is_key_path(witness: Witness) -> bool:
    """Report a key path spend: the signature alone, or plus an annex."""
    stack = witness.stack
    return len(stack) == 1 or (len(stack) == 2 and stack[-1][0] == 0x50)


def key_path_vectors(outcome: str, taproot_flag: bool) -> list[Any]:
    """Select the `outcome` vectors spending a p2tr prevout by key path.

    Selecting them here rather than skipping the others with `continue`
    inside the test is what makes the count in the report the count of
    what ran: of the 2243 vectors in the file, three quarters are not
    key path spends.

    The parse of every prevout is the price, paid once per worker at
    collection: 3 ms for the file.
    """
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if outcome not in x or (taproot_flag and "TAPROOT" not in x["flags"]):
            continue
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        if not is_key_path(Witness(x[outcome]["witness"])):
            continue
        params.append(pytest.param(x, id=vector_id(index, x["comment"])))
    return params


@pytest.mark.parametrize("vector", key_path_vectors("success", taproot_flag=True))
def test_valid_taproot_key_path(vector: dict[str, Any]) -> None:
    """Verify each success vector's signature against its sig_hash."""
    tx = Tx.parse(vector["tx"])
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    assert not vector["success"]["scriptSig"]

    witness = Witness(vector["success"]["witness"])
    tx.vin[index].script_witness = witness

    sighash_type = 0  # all
    signature = witness.stack[0][:64]
    if len(witness.stack[0]) == 65:
        sighash_type = witness.stack[0][-1]
        assert sighash_type != 0

    msg_hash = sig_hash.from_tx(prevouts, tx, index, sighash_type)

    pub_key = type_and_payload(prevouts[index].script_pub_key.script)[1]

    ssa.assert_as_valid_(msg_hash, pub_key, signature)


# the failure vectors are taken whatever their flags: a vector that
# does not ask for TAPROOT still must not verify
@pytest.mark.parametrize("vector", key_path_vectors("failure", taproot_flag=False))
def test_invalid_taproot_key_path(vector: dict[str, Any]) -> None:
    """Refuse each failure vector, as malformed or as not verifying."""
    tx = Tx.parse(vector["tx"])
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    witness = Witness(vector["failure"]["witness"])
    tx.vin[index].script_witness = witness

    # outside the raises block: inside it, with AssertionError named in
    # the tuple, a vector carrying a scriptSig would satisfy the raises
    # and the test would pass without computing a sighash at all. Made
    # here, the assertion cannot be mistaken for the refusal being
    # tested
    assert not vector["failure"]["scriptSig"]

    # the two of the contract this can legitimately leave through:
    # BTClibValueError for a malformed input and BTClibRuntimeError for
    # `ssa.assert_as_valid_` on a signature that does not verify. Neither
    # derives from the other -- ValueError against RuntimeError -- so both
    # are named, and nothing wider is
    with pytest.raises((BTClibRuntimeError, BTClibValueError)):
        sighash_type = 0  # all
        signature = witness.stack[0][:64]
        if len(witness.stack[0]) == 65:
            sighash_type = witness.stack[0][-1]
            if sighash_type == 0:
                raise BTClibValueError("invalid sighash 0 in 65 bytes signature")

        msg_hash = sig_hash.from_tx(prevouts, tx, index, sighash_type)

        pub_key = type_and_payload(prevouts[index].script_pub_key.script)[1]

        ssa.assert_as_valid_(msg_hash, pub_key, signature)


def test_valid_taproot_script_path() -> None:
    """Verify one script path spend's signature against its sig_hash."""
    tx_data = "26dc279d02d8b1a203b653fc4e0f27f408432f3f540136d33f8f930eaeba655910095142980402000000fd697cd4eb5278f1e34545cd57b6670df806fa3a0a064fd8e385a19f1a53d9ce8d8971a30f02000000378d5fb502335dbe02000000001976a9140053a23441c8478caac4c6b769c51f8476cd4b4b88ac58020000000000001976a914f2aae94a43e0d173354201d7832b46c5269c8a2488ac4a08671e"
    prevouts_data = [
        "91ca4c010000000017a9145658b58602cdf7b7e962cfe44e024cb0e366f27087",
        "cb127401000000002251201ebe8b90363bd097aa9f352c8b21914e1886bc09fe9e70c09f33ef2d2abdf4bc",
    ]
    witness_data = [
        "9675a9982c6398ea9d441cb7a943bcd6ff033cc3a2e01a0178a7d3be4575be863871c6bf3eef5ecd34721c784259385ca9101c3a313e010ac942c99de05aaaa602",
        "5799cf4b193b730fb99580b186f7477c2cca4d28957326f6f1a5d14116438530e7ec0ce1cd465ad96968ae8a6a09d4d37a060a115919f56fcfebe7b2277cc2df5cc08fb6cda9105ee2512b2e22635aba",
        "7520c7b5db9562078049719228db2ac80cb9643ec96c8055aa3b29c2c03d4d99edb0ac",
        "c1a7957acbaaf7b444c53d9e0c9436e8a8a3247fd515095d66ddf6201918b40a3668f9a4ccdffcf778da624dca2dda0b08e763ec52fd4ad403ec7563a3504d0cc168b9a77a410029e01dac89567c9b2e6cd726e840351df3f2f58fefe976200a19244150d04153909f660184d656ee95fa7bf8e1d4ec83da1fca34f64bc279b76d257ec623e08baba2cfa4ea9e99646e88f1eb1668c00c0f15b7443c8ab83481611cc3ae85eb89a7bfc40067eb1d2e6354a32426d0ce710e88bc4cc0718b99c325509c9d02a6a980d675a8969be10ee9bef82cafee2fc913475667ccda37b1bc7f13f64e56c449c532658ba8481631c02ead979754c809584a875951619cec8fb040c33f06468ae0266cd8693d6a64cea5912be32d8de95a6da6300b0c50fdcd6001ea41126e7b7e5280d455054a816560028f5ca53c9a50ee52f10e15c5337315bad1f5277acb109a1418649dc6ead2fe14699742fee7182f2f15e54279c7d932ed2799d01d73c97e68bbc94d6f7f56ee0a80efd7c76e3169e10d1a1ba3b5f1eb02369dc43af687461c7a2a3344d13eb5485dca29a67f16b4cb988923060fd3b65d0f0352bb634bcc44f2fe668836dcd0f604150049835135dc4b4fbf90fb334b3938a1f137eb32f047c65b85e6c1173b890b6d0162b48b186d1f1af8521945924ac8ac8efec321bf34f1d4b3d4a304a10313052c652d53f6ecb8a55586614e8950cde9ab6fe8e22802e93b3b9139112250b80ebc589aba231af535bb20f7eeec2e412f698c17f3fdc0a2e20924a5e38b21a628a9e3b2a61e35958e60c7f5087c",
    ]

    tx = Tx.parse(tx_data)
    prevouts = [TxOut.parse(prevout) for prevout in prevouts_data]
    index = 1
    witness = Witness(witness_data)
    tx.vin[index].script_witness = witness

    # this spend's signature carries its own hash type, so the 65th octet
    # is what it is signed under: asserted rather than branched on, the
    # witness above being one fixed transcription and not a vector file
    assert len(witness.stack[0]) == 65
    signature = witness.stack[0][:64]
    sighash_type = witness.stack[0][-1]
    assert sighash_type != 0

    msg_hash = sig_hash.from_tx(prevouts, tx, index, sighash_type)

    tapscript = parse(witness.stack[-2])
    pub_key = bytes.fromhex(str(tapscript[1]))

    ssa.assert_as_valid_(msg_hash, pub_key, signature)


def test_valid_sighash_type() -> None:
    """Verify each byte value is accepted or refused as a hash type."""
    for hash_type in range(256):
        if hash_type in sig_hash.SIG_HASH_TYPES:
            sig_hash.assert_valid_hash_type(hash_type)
        else:
            err_msg = "invalid sig_hash type: "
            with pytest.raises(BTClibValueError, match=err_msg):
                sig_hash.assert_valid_hash_type(hash_type)


def test_empty_stack() -> None:
    """Refuse to hash a p2tr spend whose witness stack is empty."""
    utxo = TxOut(
        100000000,
        serialize(
            ["OP_1", "cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaf"]
        ),
    )
    tx_in = TxIn(OutPoint(), "5151", 1, Witness([]))
    tx = Tx(vin=[tx_in], vout=[TxOut(100000000, "")])

    err_msg = "Empty stack"
    with pytest.raises(BTClibValueError, match=err_msg):
        sig_hash.from_tx([utxo], tx, 0, 0)


def test_wrapped_p2tr() -> None:
    """Refuse a taproot script wrapped in p2sh."""
    script: ScriptList = [
        "OP_1",
        "cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaf",
    ]
    utxo = TxOut(
        100000000, serialize(["OP_HASH160", hash160(serialize(script)), "OP_EQUAL"])
    )
    # the script_sig pushes the redeem script, it is not the redeem script
    script_sig = serialize([serialize(script)])
    tx_in = TxIn(OutPoint(), script_sig, 1, Witness(["0A" * 32]))
    tx = Tx(vin=[tx_in], vout=[TxOut(100000000, "")])

    err_msg = "Taproot scripts cannot be wrapped in p2sh"
    with pytest.raises(BTClibValueError, match=err_msg):
        sig_hash.from_tx([utxo], tx, 0, 0)


def annex_vectors() -> list[Any]:
    """Vectors whose witness carries an annex: nothing else can strip one."""
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if "TAPROOT" not in x["flags"]:
            continue
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) < 2 or stack[-1][0] != 0x50:
            continue  # no annex, nothing to strip
        params.append(pytest.param(x, id=vector_id(index, x["comment"])))
    return params


ANNEX_VECTORS = annex_vectors()


def test_annex_vectors_exist() -> None:
    """The test below proves nothing on an empty set of vectors.

    A parametrized test over no parameter is reported as one green
    skip, so the count is asserted here rather than not at all.
    """
    assert ANNEX_VECTORS


@pytest.mark.parametrize("vector", ANNEX_VECTORS)
def test_from_tx_does_not_touch_the_tx(vector: dict[str, Any]) -> None:
    """Computing a taproot sighash must not strip the annex from the Tx.

    Guards against `taproot_annex_and_ext` assigning the trimmed stack
    back to the witness it is handed: a second call on the same Tx then
    sees no annex and hashes a different preimage, while `tx.serialize()`
    and `tx.hash` change under the caller (issue #140).
    """
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]
    stack = Witness(vector["success"]["witness"]).stack

    tx = Tx.parse(vector["tx"])
    tx.vin[index].script_witness = Witness(stack)
    serialized = tx.serialize(include_witness=True, check_validity=False)

    msg_hash = sig_hash.from_tx(prevouts, tx, index, 0)

    assert sig_hash.from_tx(prevouts, tx, index, 0) == msg_hash
    assert tx.vin[index].script_witness.stack == stack
    assert tx.serialize(include_witness=True, check_validity=False) == serialized


KEY_PATH_SPENDING = load("script", "_data", "taproot_test_vector.json")[
    "keyPathSpending"
][0]


def unsigned_tx_and_utxos() -> tuple[Tx, list[TxOut]]:
    """Rebuild the BIP341 key path spending case for each of its inputs.

    Rebuilt rather than shared: a parameter is one object handed to every
    test that takes it, and this Tx is the argument of the very calls the
    module tests for mutating it.
    """
    tx = Tx.parse(KEY_PATH_SPENDING["given"]["rawUnsignedTx"])
    utxos = [
        TxOut(utxo["amountSats"], utxo["scriptPubKey"])
        for utxo in KEY_PATH_SPENDING["given"]["utxosSpent"]
    ]
    for vin in tx.vin:
        # a new Witness, the stack being an immutable tuple
        vin.script_witness = Witness([*vin.script_witness.stack, b"00"])
    return tx, utxos


@pytest.mark.parametrize(
    "spending",
    [
        pytest.param(
            spending,
            id=vector_id(
                index,
                f"input{spending['given']['txinIndex']}",
                f"hashtype{spending['given']['hashType']}",
            ),
        )
        for index, spending in enumerate(KEY_PATH_SPENDING["inputSpending"])
    ],
)
def test_bip_test_vector(spending: dict[str, Any]) -> None:
    """Reproduce BIP341's vectors: sig_hash, witness and tweak alike."""
    unsigned_tx, utxos = unsigned_tx_and_utxos()

    index = spending["given"]["txinIndex"]
    hash_type = spending["given"]["hashType"]
    signature_hash = sig_hash.from_tx(utxos, unsigned_tx, index, hash_type)
    assert signature_hash.hex() == spending["intermediary"]["sigHash"]

    # and now sign it, which is the half of these vectors the suite used
    # to leave on the table: the sigHash was checked and "expected", the
    # witness the BIP says that hash signs to, was not. aux_rand of 32
    # zero bytes is what BIP341 made them with, and pinning it is what
    # makes a BIP340 signature reproducible at all
    tweaked_prv_key = bytes.fromhex(spending["intermediary"]["tweakedPrivkey"])
    signature = ssa.sign_(signature_hash, tweaked_prv_key, b"\x00" * 32)
    witness_element = signature.serialize()
    # SIGHASH_DEFAULT is the 64-byte form: the type is appended only when
    # it is not the default one, and 0x00 appended is invalid (issue #122)
    if hash_type != sig_hash.DEFAULT:
        witness_element += hash_type.to_bytes(1, "big")
    assert witness_element.hex() == spending["expected"]["witness"][0]

    # verified the way issue 124 verified it, which is the correct way:
    # the key is the x-only *output* key the script carries, and the
    # message is the sig_hash itself -- hence assert_as_valid_ and sign_,
    # the spellings that do not reduce their argument with hf
    pub_key = type_and_payload(utxos[index].script_pub_key.script)[1]
    ssa.assert_as_valid_(signature_hash, pub_key, signature)

    # btclib's own tweak against the BIP's number, for the one input that
    # commits to no script: output_prvkey takes the tree, and these
    # vectors give a merkle root, so the six that have one are covered by
    # the signature above rather than here
    if spending["given"]["merkleRoot"] is None:
        internal_prv_key = bytes.fromhex(spending["given"]["internalPrivkey"])
        assert output_prvkey(internal_prv_key) == int.from_bytes(tweaked_prv_key, "big")


@pytest.mark.parametrize(
    "hash_type",
    [
        sig_hash.DEFAULT,
        sig_hash.ALL,
        sig_hash.NONE,
        sig_hash.SINGLE,
        sig_hash.ANYONECANPAY | sig_hash.ALL,
    ],
    ids=["default", "all", "none", "single", "anyonecanpay-all"],
)
@pytest.mark.parametrize(
    "script_tree", [None, [(0xC0, ["OP_1"])]], ids=["key only", "script tree"]
)
def test_key_path_spend_round_trip(hash_type: int, script_tree: Any) -> None:
    """Sign a key path spend with btclib and have btclib's engine accept it.

    The BIP341 vectors above are signed and verified against numbers the
    BIP provides; this builds the spend instead, so the tweak, the
    sig_hash, the signature, the witness encoding and the script engine
    are all btclib's. Issue 124 is the reason it exists: nothing here used
    to sign a key path spend end to end, so a caller reading the suite for
    the pattern found the verify half alone -- and the two mistakes below
    are the ones that half invites.
    """
    prv_key = 0x4242424242424242424242424242424242424242424242424242424242424242
    script_pub_key = ScriptPubKey.p2tr(prv_key, script_tree)
    prevouts = [TxOut(100_000, script_pub_key)]

    vin = TxIn(OutPoint(b"\x11" * 32, 0))
    # from_tx reads the witness to tell a key path spend from a script
    # path one, so an unsigned input still needs a placeholder in it
    vin.script_witness = Witness([b"\x00" * 64])
    tx = Tx(vin=[vin], vout=[TxOut(90_000, script_pub_key)])

    msg = sig_hash.from_tx(prevouts, tx, 0, hash_type)
    signature = ssa.sign_(msg, output_prvkey(prv_key, script_tree))
    pub_key = type_and_payload(prevouts[0].script_pub_key.script)[1]
    ssa.assert_as_valid_(msg, pub_key, signature)

    witness_element = signature.serialize()
    if hash_type != sig_hash.DEFAULT:
        witness_element += hash_type.to_bytes(1, "big")
    assert len(witness_element) == (64 if hash_type == sig_hash.DEFAULT else 65)

    # the whole point: the engine, with every flag on, spends the output
    tx.vin[0].script_witness = Witness([witness_element])
    verify_transaction(prevouts, tx)

    # the two ways issue 124 got a refusal, each on its own. sign reduces
    # its argument with hf and sign_ does not, so the pair that verifies
    # is sign_/assert_as_valid_ (or sign/assert_as_valid, which signs a
    # hash of the sig_hash and is self-consistent rather than valid on
    # the network).
    #
    # An alternation and not a bare class, because the two arms of
    # `assert_as_valid_` word it differently: libsecp256k1 answers one
    # bit and btclib says "signature verification failed", while the
    # Python arm knows which of BIP340's checks failed and says so -- "y_K
    # is odd" for these signatures. Both are BTClibRuntimeError, which is
    # the contract, and dropping the match outright would throw away in
    # both configurations a check that has held since issue #124. Issue
    # #998 is whether the wording should agree
    wrong = ssa.sign(msg, output_prvkey(prv_key, script_tree))
    with pytest.raises(BTClibRuntimeError, match=_REFUSED):
        ssa.assert_as_valid_(msg, pub_key, wrong)

    # and the key from the script is the tweaked one, the internal key
    # being what the tweak is computed from
    wrong = ssa.sign_(msg, prv_key)
    with pytest.raises(BTClibRuntimeError, match=_REFUSED):
        ssa.assert_as_valid_(msg, pub_key, wrong)


# issue 252: the script path through `from_tx`, annex and all


def has_annex(witness: Witness) -> bool:
    """BIP341's annex: a last element of at least two, starting with 0x50."""
    stack = witness.stack
    return len(stack) >= 2 and stack[-1][:1] == b"\x50"


def script_path_vectors() -> list[Any]:
    """Select the success vectors spending a `<pub_key> OP_CHECKSIG` leaf.

    The tapscript has to be one whose signature this test can check, so
    the leaf is the simplest shape Core's dump carries and the witness
    is the three elements of a bare script path spend -- signature,
    script, control block -- with or without an annex after them. 58 of
    the file's 2244 vectors qualify, 11 of them carrying an annex.

    Nothing else drives `sig_hash.from_tx` down the script path with an
    annex, which is what leaves the branch that strips one untested:
    `test_valid_taproot_script_path` below is one spend and carries
    none, and a key path spend cannot reach the branch at all -- with
    the annex off its stack holds the signature alone, so the leaf hash
    is not computed either way and dropping the wrong number of
    elements changes no answer (issue #252).
    """
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if "TAPROOT" not in x["flags"]:
            continue
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        witness = Witness(x["success"]["witness"])
        stack = witness.stack[:-1] if has_annex(witness) else witness.stack
        # signature, script, control block: no leaf takes an input off
        # the stack, so the script is always the last but one
        if len(stack) != 3 or len(stack[0]) not in {64, 65}:
            continue
        # <32-byte push> OP_CHECKSIG, and nothing else
        if len(stack[1]) != 34 or stack[1][0] != 0x20 or stack[1][-1] != 0xAC:
            continue
        params.append(pytest.param(x, id=vector_id(index, x["comment"])))
    return params


SCRIPT_PATH_VECTORS = script_path_vectors()


def test_script_path_vectors_carry_an_annex() -> None:
    """The test below covers the annex only if some vector has one.

    Both counts are asserted, not merely the total: a selector that
    stopped matching the annex cases would leave the branch this was
    written for untested again, and a green run of 47 vectors is what
    that failure would look like.
    """
    annexed = [
        vector
        for vector in SCRIPT_PATH_VECTORS
        if has_annex(Witness(vector.values[0]["success"]["witness"]))
    ]
    assert len(SCRIPT_PATH_VECTORS) == 58
    assert len(annexed) == 11


@pytest.mark.parametrize("vector", SCRIPT_PATH_VECTORS)
def test_valid_taproot_script_path_vectors(vector: dict[str, Any]) -> None:
    """Sign-side script path spends, which only these vectors exercise.

    `from_tx` builds the BIP342 message extension for a script path
    spend -- the leaf hash of the script under the control block -- and
    strips the annex before reading either. The signature Core's dump
    carries is the authority on the result: it verifies against the key
    in the leaf if and only if the hash is the one Core computed.
    """
    tx = Tx.parse(vector["tx"])
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    assert not vector["success"]["scriptSig"]

    witness = Witness(vector["success"]["witness"])
    tx.vin[index].script_witness = witness
    stack = witness.stack[:-1] if has_annex(witness) else witness.stack

    signature = stack[0]
    hash_type = signature[-1] if len(signature) == 65 else 0

    msg_hash = sig_hash.from_tx(prevouts, tx, index, hash_type)

    # the selector pinned the leaf to <32-byte push> OP_CHECKSIG
    pub_key = stack[1][1:33]
    ssa.assert_as_valid_(msg_hash, pub_key, signature[:64])


def test_taproot_sighash_single_past_the_last_output() -> None:
    """Every index past the last output is refused, not merely the first.

    BIP341 has no out-of-range rule to apply: "if hash_type & 3 equals
    SIGHASH_SINGLE and the input index is equal to or greater than the
    number of outputs, fail". Bitcoin Core's SignatureHashSchnorr
    returns false there, and btclib raises.

    Equal to *or greater than*, and it is the second half no vector
    states: `script_assets_test.json` carries seven spends with
    SIGHASH_SINGLE and no output of their own, and in every one of them
    the index is exactly the output count -- so a bound written `==`
    passes the whole file (issue #252).
    """
    prv_key = 0x4242424242424242424242424242424242424242424242424242424242424242
    script_pub_key = ScriptPubKey.p2tr(prv_key)
    prevouts = [TxOut(100_000, script_pub_key) for _ in range(3)]

    vin = [TxIn(OutPoint(bytes([i + 1]) * 32, 0)) for i in range(3)]
    for tx_in in vin:
        # from_tx reads the witness to tell a key path spend from a
        # script path one, so an unsigned input needs a placeholder
        tx_in.script_witness = Witness([b"\x00" * 64])
    tx = Tx(vin=vin, vout=[TxOut(90_000, script_pub_key)])

    # the input that has an output of its own commits to it
    assert sig_hash.from_tx(prevouts, tx, 0, sig_hash.SINGLE)

    err_msg = "Sighash single without a corresponding output"
    for vin_i in (1, 2):
        with pytest.raises(BTClibValueError, match=err_msg):
            sig_hash.from_tx(prevouts, tx, vin_i, sig_hash.SINGLE)
        # ANYONECANPAY changes what else is committed to, not this
        with pytest.raises(BTClibValueError, match=err_msg):
            sig_hash.from_tx(
                prevouts, tx, vin_i, sig_hash.ANYONECANPAY | sig_hash.SINGLE
            )


@pytest.mark.parametrize("annex", [b"", b"\x50" + b"\x99" * 8], ids=["bare", "annex"])
def test_script_path_spend_round_trip(annex: bytes) -> None:
    """Sign a script path spend with btclib and have btclib's engine take it.

    The signer's witness is the shape no vector can carry: script and
    control block, with no signature on the stack yet, because the
    signature is what this call is for. Dropping the annex has to leave
    two elements there, and the leaf hash the message extension commits
    to is read off both of them -- so a bound that wanted three, as
    `len(stack) > 2` would, computes a key path message instead and the
    engine, which strips the annex in its own code, rejects what comes
    back (issue #252).

    The engine is the second implementation that makes this a check
    rather than a restatement: it reaches the leaf through the control
    block and the taproot commitment, and never calls `from_tx`.
    """
    internal_key = 0x4242424242424242424242424242424242424242424242424242424242424242
    leaf_prv_key = 0x1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF
    leaf_pub_key = pub_keyinfo_from_prv_key(leaf_prv_key)[0][1:]

    script_tree: TaprootScriptTree = [(0xC0, [leaf_pub_key.hex(), "OP_CHECKSIG"])]
    script_pub_key = ScriptPubKey.p2tr(internal_key, script_tree)
    leaf, control = input_script_sig(internal_key, script_tree, 0)
    leaf_bytes = taproot_serialize(leaf)

    prevouts = [TxOut(100_000, script_pub_key)]
    vin = TxIn(OutPoint(b"\x11" * 32, 0))
    # what the signer holds: the spend without its signature
    unsigned_stack = [leaf_bytes, control, annex] if annex else [leaf_bytes, control]
    vin.script_witness = Witness(unsigned_stack)
    tx = Tx(vin=[vin], vout=[TxOut(90_000, script_pub_key)])

    msg_hash = sig_hash.from_tx(prevouts, tx, 0, sig_hash.DEFAULT)
    signature = ssa.sign_(msg_hash, leaf_prv_key)
    ssa.assert_as_valid_(msg_hash, leaf_pub_key, signature)

    tx.vin[0].script_witness = Witness([signature.serialize(), *unsigned_stack])
    verify_transaction(prevouts, tx)

    # the signature on the stack is not part of what is signed: the same
    # message comes back out of the completed spend
    assert sig_hash.from_tx(prevouts, tx, 0, sig_hash.DEFAULT) == msg_hash


def test_the_spent_amounts_are_signed_camounts() -> None:
    """BIP341's sha_amounts holds CAmounts, so its eight-byte words are signed.

    Every amount is a spent output's value, a signed int64 (issue #388),
    and Core hashes them with `ss << txout.nValue` -- so what
    `TxOut.parse` reads with the check off must be what this commits to.
    Eight `ff` octets are -1, and the field carries those octets: the
    hash is the one an unsigned reading of the same buffer produced,
    which is the point, only the integer naming them having moved.
    """
    high_bit_set = b"\xff" * 8 + b"\x00"  # the value, then an empty script
    prevout = TxOut.parse(high_bit_set, check_validity=False)
    assert prevout.value == -1

    tx = Tx(
        1,
        0,
        [TxIn(OutPoint(b"\x11" * 32, 0), b"", 0xFFFFFFFF, Witness([b"\x00" * 64]))],
        [TxOut(1000, "00141d0f172a0ecb48aee1be1f2687d2963ae33f71a1")],
    )

    # the octets, and the two entry points that write them: neither
    # raises the OverflowError an unsigned field answers -1 with
    precomputed = sig_hash.PrecomputedTxData(tx, [prevout])
    assert precomputed.sha_amounts == sha256(b"\xff" * 8)
    assert sig_hash.taproot(tx, 0, [prevout], sig_hash.DEFAULT, 0, b"", b"")

    # and ANYONECANPAY, which writes the one amount inline instead
    assert sig_hash.taproot(
        tx, 0, [prevout], sig_hash.ANYONECANPAY | sig_hash.ALL, 0, b"", b""
    )


def test_an_input_index_outside_the_vin_is_refused() -> None:
    """Two indexes of no input gave two hashes, both accepted as answers.

    BIP341's SigMsg commits to the index itself, and outside the
    ANYONECANPAY branch that is all it does with it: nothing dereferences
    `transaction.vin[input_index]`, so an index past the end was written
    into the preimage and hashed. 99 and 100 on a two-input transaction
    therefore produced two *different* 32-byte hashes, each a valid
    answer to a question about an input that does not exist. The bound
    was checked in the SIGHASH_SINGLE branch alone, against the vout.
    """
    utxo = TxOut(
        100000000,
        serialize(
            ["OP_1", "cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaf"]
        ),
    )
    vin = [
        TxIn(OutPoint("01" * 32, 0), "", 1, Witness(["00" * 64])),
        TxIn(OutPoint("02" * 32, 1), "", 1, Witness(["00" * 64])),
    ]
    tx = Tx(vin=vin, vout=[TxOut(100000000, ""), TxOut(1, "")])
    prevouts = [utxo, utxo]

    def sig_hash_of(input_index: int) -> bytes:
        return sig_hash.taproot(tx, input_index, prevouts, 0x01, 0, b"", b"")

    assert len(sig_hash_of(0)) == 32
    assert sig_hash_of(0) != sig_hash_of(1)

    for out_of_range in (-1, 2, 99, 100):
        with pytest.raises(BTClibValueError, match="invalid input index: "):
            sig_hash_of(out_of_range)
    for not_an_index in (1.0, "0", True):
        with pytest.raises(BTClibTypeError, match="invalid input index type: "):
            sig_hash_of(not_an_index)  # type: ignore[arg-type]


def _two_input_p2tr() -> tuple[Tx, list[TxOut]]:
    """Return a two-input p2tr spend and the prevouts it spends."""
    utxo = TxOut(
        100000000,
        serialize(
            ["OP_1", "cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaf"]
        ),
    )
    vin = [
        TxIn(OutPoint("01" * 32, 0), "", 1, Witness(["00" * 64])),
        TxIn(OutPoint("02" * 32, 1), "", 1, Witness(["00" * 64])),
    ]
    tx = Tx(vin=vin, vout=[TxOut(100000000, ""), TxOut(1, "")])
    return tx, [utxo, utxo]


def test_every_width_the_bip341_preimage_writes_is_checked() -> None:
    """SigMsg is assembled here too, and never through `Tx.serialize`.

    The sequence and the outpoint are written only under ANYONECANPAY,
    which commits to the signed input alone; without it they reach the
    preimage through `sha_sequences` and `sha_prevouts`, so both hash
    types are asked.
    """
    tx, prevouts = _two_input_p2tr()

    def sig_hash_of(transaction: Tx, hashtype: int) -> bytes:
        return sig_hash.taproot(transaction, 0, prevouts, hashtype, 0, b"", b"")

    for field, err_msg in (
        ("version", "invalid version: "),
        ("lock_time", "invalid lock time: "),
    ):
        bad, _ = _two_input_p2tr()
        setattr(bad, field, 2**32)
        with pytest.raises(BTClibValueError, match=err_msg):
            sig_hash_of(bad, sig_hash.ALL)

    for hashtype in (sig_hash.ALL, sig_hash.ALL | sig_hash.ANYONECANPAY):
        bad, _ = _two_input_p2tr()
        bad.vin[0].sequence = 2**32
        with pytest.raises(BTClibValueError, match="invalid sequence: "):
            sig_hash_of(bad, hashtype)

        bad, _ = _two_input_p2tr()
        bad.vin[0] = TxIn(
            OutPoint(b"\x01" * 32, 2**32, check_validity=False),
            b"",
            1,
            Witness(["00" * 64]),
            check_validity=False,
        )
        with pytest.raises(BTClibValueError, match="invalid vout: "):
            sig_hash_of(bad, hashtype)

    bad, _ = _two_input_p2tr()
    bad.vout[0] = TxOut(2**63, bad.vout[0].script_pub_key, check_validity=False)
    with pytest.raises(BTClibValueError, match="invalid output value: "):
        sig_hash_of(bad, sig_hash.SINGLE)

    assert len(sig_hash_of(tx, sig_hash.ALL)) == 32


def test_the_spend_type_byte_holds_seven_bits_of_extension_flag() -> None:
    """`(2 * ext_flag + annex_present).to_bytes(1)` was an OverflowError.

    BIP341's spend type is one byte, so the flag is 0 for a key path, 1
    for BIP342's tapscript, and nothing wider has anywhere to go.
    """
    tx, prevouts = _two_input_p2tr()

    def sig_hash_with(ext_flag: int) -> bytes:
        return sig_hash.taproot(tx, 0, prevouts, sig_hash.ALL, ext_flag, b"", b"")

    # the boundary itself, not only one past it
    assert len(sig_hash_with(0x7F)) == 32
    for out_of_range in (-1, 0x80, 2**40):
        with pytest.raises(BTClibValueError, match="invalid extension flag: "):
            sig_hash_with(out_of_range)
    for not_a_flag in (1.0, "0", True):
        with pytest.raises(BTClibTypeError, match="invalid extension flag type: "):
            sig_hash_with(not_a_flag)  # type: ignore[arg-type]


def test_the_message_extension_is_octets_like_every_other_field() -> None:
    """It is concatenated raw, where the annex goes through var_bytes.

    So a hex string -- which every other octets parameter of this library
    takes -- met `b"".join` and answered `TypeError: sequence item 11`,
    from underneath the library and about the join rather than about the
    argument.
    """
    tx, prevouts = _two_input_p2tr()
    ext = b"\x01" * 37

    def sig_hash_with(message_extension: Octets) -> bytes:
        return sig_hash.taproot(
            tx, 0, prevouts, sig_hash.ALL, 1, b"", message_extension
        )

    assert sig_hash_with(ext) == sig_hash_with(ext.hex())
    with pytest.raises(BTClibValueError, match="invalid hex string: "):
        sig_hash_with("not hex at all")


def test_from_tx_names_an_input_both_lists_have() -> None:
    """`prevouts[vin_i]` and `tx.vin[vin_i]` were two unchecked indexes.

    And nothing asked whether the two lists were of one length, which
    `PrecomputedTxData` does refuse and `verify_transaction` before it: a
    prevout list shorter than the vin hashes the amounts of one
    transaction into the sig_hash of another.
    """
    tx, prevouts = _two_input_p2tr()
    assert len(sig_hash.from_tx(prevouts, tx, 1, sig_hash.ALL)) == 32

    for out_of_range in (-1, 2, 99):
        with pytest.raises(BTClibValueError, match="invalid input index: "):
            sig_hash.from_tx(prevouts, tx, out_of_range, sig_hash.ALL)
        with pytest.raises(BTClibValueError, match="invalid input index: "):
            sig_hash.taproot_annex_and_ext(tx, out_of_range)

    err_msg = "1 prevouts for 2 transaction inputs"
    with pytest.raises(BTClibValueError, match=err_msg):
        sig_hash.from_tx(prevouts[:1], tx, 0, sig_hash.ALL)
