# Copyright (c) The btclib developers
#
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""Tests for the `btclib.script.taproot` module.

The same two vendored files as `sig_hash_taproot_test.py`, and the same
distinction: `taproot_test_vector.json` is bip-0341's
`wallet-test-vectors.json`, while `script_assets_test.json` keeps the name
it has in `unit_test_data/` of bitcoin-core/qa-assets, a dump generated by
Core rather than anything a BIP publishes.
tests/_data/README.md pins the revision of each.
"""

from typing import Any

import pytest

from btclib import b32
from btclib.alias import ScriptList
from btclib.curves import mult
from btclib.exceptions import BTClibValueError
from btclib.script import (
    TaprootScriptTree,
    Witness,
    check_output_pubkey,
    input_script_sig,
    is_p2tr,
    output_prvkey,
    output_pubkey,
    taproot,
    type_and_payload,
)
from btclib.script.taproot import parse, serialize
from btclib.tx import TxOut
from tests import load, vector_id
from tests.curves.curve_test import low_card_curves
from tests.script import serialize_non_canonical


def script_path_vectors() -> list[Any]:
    """Collect the vectors spending a p2tr prevout through a script path.

    The two `continue` of the loop: a prevout that is not p2tr, and a
    witness with nothing but a signature on it once the annex is off.
    """
    params = []
    for index, x in enumerate(load("script", "_data", "script_assets_test.json")):
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) >= 2 and stack[-1][0] == 0x50:
            stack = stack[:-1]  # drop the annex
        if len(stack) < 2:
            continue
        params.append(pytest.param(x, id=vector_id(index, x["comment"])))
    return params


@pytest.mark.parametrize("vector", script_path_vectors())
def test_valid_script_path(vector: dict[str, Any]) -> None:
    """Verify each vector's control block commits to its output key."""
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    assert not vector["success"]["scriptSig"]

    witness = Witness(vector["success"]["witness"])
    if len(witness.stack) >= 2 and witness.stack[-1][0] == 0x50:
        witness = Witness(witness.stack[:-1])  # drop the annex

    Q = type_and_payload(prevouts[index].script_pub_key.script)[1]

    script = witness.stack[-2]
    control = witness.stack[-1]

    assert check_output_pubkey(Q, script, control)


# the key path, one leaf and a two-leaf branch: the three shapes a tweak
# can commit to, shared by the tests below rather than spelled out in
# each -- what they must agree about is the tweak, not the tree
SCRIPT_TREES: list[TaprootScriptTree | None] = [
    None,
    [(0xC0, ["OP_1"])],
    [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]],
]


def test_taproot_key_tweaking() -> None:
    """Verify the tweaked private key generates the tweaked public key."""
    prv_key = 123456
    pub_key = mult(prv_key)

    for script_tree in SCRIPT_TREES:
        tweaked_prvkey = output_prvkey(prv_key, script_tree)
        tweaked_pubkey = output_pubkey(pub_key, script_tree)[0]

        assert tweaked_pubkey == mult(tweaked_prvkey)[0].to_bytes(32, "big")


def test_the_python_tweak_is_the_bindings_tweak(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Both output keys, computed twice, are the same keys on secp256k1.

    The bindings are the authority on the answer and the Python
    arithmetic is the reference implementation of it, so what has to be
    asserted is that the two are one answer. It takes the patch because
    there is no second curve to reach the Python path with: a toy curve
    fails the BIP341 range check on a 256-bit tweak before any
    arithmetic happens, and taproot is defined over secp256k1 alone.

    The private key is the one whose public point has an odd y, the case
    the tweaking negates: with an even one the two paths would agree
    over a negation neither of them performed.
    """
    prv_key = 0xC0FFEE
    pub_key = mult(prv_key)
    assert pub_key[1] % 2 == 1

    for script_tree in SCRIPT_TREES:
        delegated = output_pubkey(pub_key, script_tree)
        delegated_prvkey = output_prvkey(prv_key, script_tree)
        with monkeypatch.context() as no_bindings:
            no_bindings.setattr(taproot, "_libsecp256k1_applicable", lambda *_: False)
            assert output_pubkey(pub_key, script_tree) == delegated
            assert output_prvkey(prv_key, script_tree) == delegated_prvkey


def test_the_python_commitment_check_is_the_bindings_one(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The control block verdict, taken twice, is the same verdict.

    Both verdicts, because a check that only ever says True is a check
    that says nothing: the false one is the same output key with a byte
    flipped, which commits to nothing and must fail on either path.
    """
    pub_key = mult(0xC0FFEE)
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    q = output_pubkey(pub_key, script_tree)[0]
    not_q = bytes([q[0] ^ 1]) + q[1:]
    script, control = input_script_sig(pub_key, script_tree, 0)
    script_bytes = serialize(script)

    assert check_output_pubkey(q, script_bytes, control)
    assert not check_output_pubkey(not_q, script_bytes, control)
    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_applicable", lambda *_: False)
        assert check_output_pubkey(q, script_bytes, control)
        assert not check_output_pubkey(not_q, script_bytes, control)


def test_check_output_pubkey_of_a_key_that_is_not_32_bytes() -> None:
    """A q of another length is answered, not refused.

    `tweak_add_check` takes 32 bytes and raises for anything else, so
    the dispatch asks for that size and leaves every other q to the
    Python comparison. Which is not a length test but an integer one:
    it says no to a truncated key and yes to a zero-padded one, and
    that second answer is why the dispatch falls through here instead
    of turning the size into a refusal.
    """
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(None, script_tree)[0]
    script, control = input_script_sig(None, script_tree, 0)

    assert not check_output_pubkey(pub_key[:31], serialize(script), control)
    assert check_output_pubkey(b"\x00" + pub_key, serialize(script), control)


def test_check_output_pubkey_of_an_internal_key_that_is_not_a_point(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Both paths refuse an internal key with no y, and refuse it alike.

    x = 5 is not the x-coordinate of a secp256k1 point: 5**3 + 7 is not
    a quadratic residue. libsecp256k1 rejects it while parsing and
    ec.y_even while lifting it, and the two errors have to be the same
    kind, the script engine catching the library's own.
    """
    control = b"\xc0" + (5).to_bytes(32, "big")
    err_msg = "invalid"

    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x51", control)
    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_applicable", lambda *_: False)
        with pytest.raises(BTClibValueError, match=err_msg):
            check_output_pubkey(b"\x00" * 32, b"\x51", control)


def test_invalid_control_block() -> None:
    """Refuse a control block too long or of an invalid length."""
    err_msg = "control block too long"
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x00", b"\x00" * 4130)

    err_msg = "invalid control block length"
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x00", b"\x00" * 100)


def test_unspendable_script() -> None:
    """Refuse output_pubkey with neither a key nor a script tree."""
    err_msg = "missing data"
    with pytest.raises(BTClibValueError, match=err_msg):
        output_pubkey()


def test_control_block() -> None:
    """Verify input_script_sig's control block passes the BIP341 check."""
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(None, script_tree)[0]
    script, control = input_script_sig(None, script_tree, 0)
    assert check_output_pubkey(pub_key, serialize(script), control)

    prv_key = 123456
    internal_pubkey = mult(prv_key)
    script_tree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(internal_pubkey, script_tree)[0]
    script, control = input_script_sig(internal_pubkey, script_tree, 0)
    assert check_output_pubkey(pub_key, serialize(script), control)


# the vector's scriptTree, not a tree: nested json lists of
# {"leafVersion": ..., "script": ...} objects, hence Any in and a real
# TaprootScriptTree out -- each leaf a tuple, the one shape the alias
# names, not a two-element list that happens to unpack the same way
def convert_script_tree(script_tree: Any) -> TaprootScriptTree:
    """Convert a vector's scriptTree json into a TaprootScriptTree."""
    if isinstance(script_tree, list):
        return [convert_script_tree(x) for x in script_tree]
    if isinstance(script_tree, dict):
        return [(script_tree["leafVersion"], parse(script_tree["script"]))]
    return []


@pytest.mark.parametrize(
    "test",
    [
        pytest.param(test, id=vector_id(index, test["given"]["internalPubkey"][:16]))
        for index, test in enumerate(
            load("script", "_data", "taproot_test_vector.json")["scriptPubKey"]
        )
    ],
)
def test_bip_test_vector(test: dict[str, Any]) -> None:
    """Reproduce bip-0341's wallet vectors: tweaked key and address."""
    pub_key = test["given"]["internalPubkey"]
    script_tree = convert_script_tree(test["given"]["scriptTree"])

    tweaked_pubkey = output_pubkey(f"02{pub_key}", script_tree)[0]
    address = b32.p2tr(tweaked_pubkey)

    assert tweaked_pubkey.hex() == test["intermediary"]["tweakedPubkey"]
    assert address == test["expected"]["bip350Address"]


def test_serialize_op_success() -> None:
    """Parse an OP_SUCCESS byte, with and without exit_on_op_success."""
    assert parse(b"\x01\x00\x7e", exit_on_op_success=True) == ["OP_SUCCESS"]

    assert parse(b"\x7e\x02\x01") == ["OP_SUCCESS126", b"\x02\x01"]


def test_serialize_bytes_command() -> None:
    """Verify the push-length encoding grows at 76 and 256 bytes."""
    length = 75
    b = b"\x0a" * length
    assert len(serialize([b])) == length + 1
    b = b"\x0a" * (length + 1)
    assert len(serialize([b])) == (length + 1) + 2

    length = 255
    b = b"\x0a" * length
    assert len(serialize([b])) == length + 2
    b = b"\x0a" * (length + 1)
    assert len(serialize([b])) == (length + 1) + 3


def test_invalid_serialization() -> None:
    """Refuse a non-hex push and an OP_SUCCESS not followed by bytes."""
    with pytest.raises(BTClibValueError):
        serialize(["AAA"])

    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80"])

    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80", 1])
    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80", "00"])


def test_parse_unknown_op_code() -> None:
    """0xff is neither an OP_SUCCESS nor a named op code."""
    with pytest.raises(BTClibValueError, match="unknown op code: 0xff"):
        parse(b"\xff")


def test_serialization() -> None:
    """Round-trip scripts, small integers as data pushes included."""
    script: ScriptList = ["OP_SUCCESS80", b"\x01\x01\x01"]
    assert parse(serialize(script)) == script

    # -1 and [0, 16] are the integers with a one-byte op code, so every
    # serialize() below pushes data where an op code would do and warns
    assert parse(serialize_non_canonical([-1], serialize)) == ["81"]
    for x in range(17):
        assert parse(serialize_non_canonical([x], serialize)) == [f"{x:02X}"]

    for x in range(17, 100):
        assert parse(serialize([x])) == [f"{x:02X}"]


def test_tweak_above_group_order() -> None:
    """BIP341 rejects a tweak t that is not below the curve order.

    With secp256k1 that is a 2**-128 tagged-hash accident; a toy curve
    makes the same guard fire deterministically, since the 256-bit
    tweak always exceeds its order. Not output_prvkey, though: there
    the toy curve fails earlier, on the y parity of a secp256k1 point.
    """
    ec = low_card_curves["ec13_11"]
    err_msg = "Invalid script tree hash"

    script_tree: TaprootScriptTree = [(0xC0, ["OP_1"])]
    with pytest.raises(BTClibValueError, match=err_msg):
        output_pubkey(None, script_tree, ec)

    q = bytes(31) + b"\x01"
    control = b"\xc0" + bytes(32)
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(q, "51", control, ec)
