# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""Tests for the `btclib.script.taproot` module.

The same two vendored files as `sig_hash_taproot_test.py`, and the same
distinction: `taproot_test_vector.json` is bip-0341's
`wallet-test-vectors.json`, while `script_assets_test.json` keeps the name
it has in `unit_test_data/` of bitcoin-core/qa-assets, a dump generated by
Core rather than anything a BIP publishes.
tests/_data/README.md pins the revision of each.
"""

from collections.abc import Callable
from typing import Any

import pytest

from btclib import b32
from btclib._libsecp256k1 import xonly as libsecp256k1_xonly
from btclib.alias import Octets, ScriptList
from btclib.curves import bytes_from_point, curve, curve_group, mult, secp256k1
from btclib.exceptions import BTClibTypeError, BTClibValueError
from btclib.number_theory import mod_sqrt_var
from btclib.script import (
    TaprootScriptTree,
    Witness,
    check_output_pubkey,
    input_script_sig,
    is_p2tr,
    output_prvkey,
    output_prvkey_from_merkle_root,
    output_pubkey,
    output_pubkey_from_merkle_root,
    taproot,
    type_and_payload,
)
from btclib.script.limits import MAX_SCRIPT_ELEMENT_SIZE
from btclib.script.taproot import (
    assert_valid_control_block,
    parse,
    serialize,
    tree_helper,
)
from btclib.to_pub_key import Key
from btclib.tx import TxOut
from tests import load, needs_bindings, vector_id
from tests.curves.curve_test import low_card_curves, no_bindings_anywhere
from tests.script import serialize_non_canonical


def script_path_vectors() -> list[Any]:
    """Collect the vectors spending a p2tr prevout through a script path.

    The two `continue` of the loop: a prevout that is not p2tr, and a
    witness with nothing but a signature on it once the annex is off.
    """
    params = []
    for index, x in enumerate(load("script", "_data", "script_assets_test.json")):
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) >= 2 and stack[-1][0] == 0x50:
            stack = stack[:-1]  # drop the annex
        if len(stack) < 2:
            continue
        params.append(pytest.param(x, id=vector_id(index, x["comment"])))
    return params


@pytest.mark.parametrize("vector", script_path_vectors())
def test_valid_script_path(vector: dict[str, Any]) -> None:
    """Verify each vector's control block commits to its output key."""
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    assert not vector["success"]["scriptSig"]

    witness = Witness(vector["success"]["witness"])
    if len(witness.stack) >= 2 and witness.stack[-1][0] == 0x50:
        witness = Witness(witness.stack[:-1])  # drop the annex

    Q = type_and_payload(prevouts[index].script_pub_key.script)[1]

    script = witness.stack[-2]
    control = witness.stack[-1]

    assert check_output_pubkey(Q, script, control)


# the key path, one leaf and a two-leaf branch: the three shapes a tweak
# can commit to, shared by the tests below rather than spelled out in
# each -- what they must agree about is the tweak, not the tree
SCRIPT_TREES: list[TaprootScriptTree | None] = [
    None,
    [(0xC0, ["OP_1"])],
    [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]],
]


def test_taproot_key_tweaking() -> None:
    """Verify the tweaked private key generates the tweaked public key."""
    prv_key = 123456
    pub_key = mult(prv_key)

    for script_tree in SCRIPT_TREES:
        tweaked_prvkey = output_prvkey(prv_key, script_tree)
        tweaked_pubkey = output_pubkey(pub_key, script_tree)[0]

        assert tweaked_pubkey == mult(tweaked_prvkey)[0].to_bytes(32, "big")


def test_one_internal_key_however_it_is_spelled(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Every spelling of an internal key names the same output key (issue 896).

    The 65-byte SEC form is the one that moved: `output_pubkey` read its key
    through `pub_keyinfo_from_key(..., compressed=True)`, where the flag was
    a filter as well as a conversion and refused that length, and it reads
    `compressed=None` now because that is what has the point to hand down.
    Nothing in this file built an uncompressed key, so the widening had no
    assertion and statement coverage could not supply one: the same lines
    run for a 33-byte key.

    `input_script_sig` is asserted beside it because the two take one
    internal key between them -- it reads the parity of the output key and
    carries the key itself in the control block -- and they answer for the
    same spellings by sharing one reader rather than by agreeing. Both
    arithmetics, because the arms read the key differently: the bindings one
    wants the octets alone and the Python one the point.

    The buffers are here because the key reaches the tweak as octets to be
    concatenated, and a memoryview is not one: what makes them octets is
    `bytes_from_octets` returning `bytes` rather than the buffer it was
    given.
    """
    prv_key = 0xC0FFEE
    point = mult(prv_key)
    sec = bytes_from_point(point, compressed=True)
    spellings: tuple[Key, ...] = (
        point,
        sec,
        bytes_from_point(point, compressed=False),
        bytearray(sec),
        memoryview(sec),
    )

    for script_tree in SCRIPT_TREES:
        expected = output_pubkey(point, script_tree)
        for key in spellings:
            assert output_pubkey(key, script_tree) == expected
            with monkeypatch.context() as no_bindings:
                no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
                assert output_pubkey(key, script_tree) == expected

    # and the control block carries the same internal key from any of them,
    # which is the half a second reader of the key could get wrong
    for script_tree in SCRIPT_TREES[1:]:
        assert script_tree is not None  # the None of SCRIPT_TREES is key path only
        expected_sig = input_script_sig(point, script_tree, 0)
        for key in spellings:
            assert input_script_sig(key, script_tree, 0) == expected_sig


def test_the_python_tweak_is_the_bindings_tweak(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Both output keys, computed twice, are the same keys on secp256k1.

    The bindings are the authority on the answer and the Python
    arithmetic is the reference implementation of it, so what has to be
    asserted is that the two are one answer. It takes the patch because
    there is no second curve to reach the Python path with: a toy curve
    fails the BIP341 range check on a 256-bit tweak before any
    arithmetic happens, and taproot is defined over secp256k1 alone.

    The private key is the one whose public point has an odd y, the case
    the tweaking negates: with an even one the two paths would agree
    over a negation neither of them performed.
    """
    prv_key = 0xC0FFEE
    pub_key = mult(prv_key)
    assert pub_key[1] % 2 == 1

    for script_tree in SCRIPT_TREES:
        delegated = output_pubkey(pub_key, script_tree)
        delegated_prvkey = output_prvkey(prv_key, script_tree)
        with monkeypatch.context() as no_bindings:
            no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
            assert output_pubkey(pub_key, script_tree) == delegated
            assert output_prvkey(prv_key, script_tree) == delegated_prvkey


@pytest.mark.parametrize(
    "compressed, roots",
    [(True, 1), (False, 0)],
    ids=["compressed", "uncompressed"],
)
def test_the_python_output_key_lifts_the_internal_x_once(
    compressed: bool, roots: int, monkeypatch: pytest.MonkeyPatch
) -> None:
    """One reading of the internal key is one square root, not two.

    Two things want the internal key's point: proving the octets are one,
    and adding tG to it. Taken separately those are two modular square
    roots of the same x -- issue 896, which is 74 of the 311 us an output
    key cost on this arm. `PubKeyData` is what makes them one: `point` is
    a `cached_property`, so the lift is the proof and the proof is the
    lift (issue #1188).

    Counting `mod_sqrt_var` rather than forbidding it, which is what
    `test_the_python_prvkey_tweak_lifts_nothing` does below: here the
    right answer is not zero, and a test that only refused a second root
    would pass on a function that took none and answered nothing.

    Both SEC forms, because they are the two sides of what is being
    asserted: 65 octets carry the y and must lift nothing at all, and 33
    are exactly the x a second reader would have lifted again.

    `input_script_sig` beside `output_pubkey` because they are the two
    readers of `_output_pubkey_and_internal_key`, and reading it twice is
    the shape the count would otherwise hide.

    The dispatch goes off at `curve._libsecp256k1_available` and not at
    this module's own guard, which is what the test below patches: the
    lift is `point_from_octets`', and that call delegates on its own, so
    silencing taproot alone leaves the square root being taken in C where
    `mod_sqrt_var` never sees it. A count needs every arm Python; a test
    asserting zero, as that one does, does not.
    """
    pub_key = bytes_from_point(mult(0xC0FFEE), compressed=compressed)
    roots_taken = 0

    # `number_theory` and not the `curve_group` binding being patched: the
    # two are one function, and reading it off the module that exports it
    # is what strict mypy allows -- an attribute an `__all__` does not
    # name cannot be read, only set
    def counting(a: int, p_: int) -> int:
        nonlocal roots_taken
        roots_taken += 1
        return mod_sqrt_var(a, p_)

    for tree in SCRIPT_TREES:
        with monkeypatch.context() as no_bindings:
            no_bindings.setattr(curve, "_libsecp256k1_available", False)
            no_bindings.setattr(curve_group, "mod_sqrt_var", counting)

            roots_taken = 0
            output_pubkey(pub_key, tree)
            assert roots_taken == roots

            if tree is not None:
                roots_taken = 0
                input_script_sig(pub_key, tree, 0)
                assert roots_taken == roots


@pytest.mark.parametrize(
    "prv_key, parity", [(0xC0FFEE, 1), (3, 0)], ids=["odd y", "even y"]
)
def test_the_python_prvkey_tweak_lifts_nothing(
    prv_key: int, parity: int, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The internal key's parity is read off its y, not recomputed.

    BIP341 negates the key whose public point has an odd y, and the
    point is one `mult` has just returned: the y is in hand, so the
    parity is a `%` and not a lift of the x back to the point it came
    from (issue 619). What pins that is reaching no modular square root
    at all, which is stronger than a stopwatch and does not depend on
    the machine: mod_sqrt_var is patched to raise.

    Both parities, because the branch this reads decides a negation:
    with only the even key the answer would be right for a run that
    never took it. The parity is asserted rather than trusted to the
    id, a key whose point moved being a test that stopped testing.

    The Python path is what the patch reaches -- the bindings answer the
    whole tweak for secp256k1, and taproot is defined over no other
    curve -- and its answer still has to be the bindings' answer.
    """
    assert mult(prv_key)[1] % 2 == parity
    delegated = [output_prvkey(prv_key, tree) for tree in SCRIPT_TREES]

    def refuse(*_: object) -> int:
        raise AssertionError(  # pragma: no cover
            "the internal point's x was lifted to read a parity"
        )

    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
        no_bindings.setattr(curve_group, "mod_sqrt_var", refuse)
        for tree, expected in zip(SCRIPT_TREES, delegated, strict=True):
            assert output_prvkey(prv_key, tree) == expected


@needs_bindings
def test_the_py_arm_reaches_no_bindings(monkeypatch: pytest.MonkeyPatch) -> None:
    """Both tweaks this module gates must be Python throughout.

    A mixed arm is the one shape that is never right: with libsecp256k1 in
    reach `libsecp256k1_xonly.tweak_add` and `.prvkey_tweak_add` are the
    better calls, and out of reach there is nothing to mix.
    `_tweaked_pubkey`'s tweak and `_tweaked_prvkey`'s are that shape,
    gated on `secp256k1` and nothing else, and `output_pubkey` together
    with `output_prvkey` reach both between them.

    `check_output_pubkey`'s guard is not: it adds `len(q) == 32` to the
    same predicate, so with the bindings in reach and a q of another
    length its Python arm still runs, and that arm calls `mult`, which
    delegates on its own -- the mixed arm SECURITY.md documents for dsa
    and ssa, real there for the same reason it is real here. That guard
    is left out of this test on purpose; the fallthrough it takes with
    the bindings installed is what
    `test_check_output_pubkey_of_a_key_that_is_not_32_bytes` exercises.

    `no_bindings_anywhere` is the check `tests.bip32.bip32_test` uses for
    the same shape: it puts the whole of btclib_secp256k1 out of reach,
    module and already-bound name alike, and switches the dispatch off.
    """
    prv_key = 0xC0FFEE
    pub_key = mult(prv_key)
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    # what the bindings answer, taken while they are still in reach
    delegated = (
        output_pubkey(pub_key, script_tree),
        output_prvkey(prv_key, script_tree),
    )

    no_bindings_anywhere(monkeypatch)

    # the two taproot itself would have called, so that a walk reaching
    # nothing would fail here rather than pass by touching nothing
    with pytest.raises(AssertionError, match="reached libsecp256k1"):
        libsecp256k1_xonly.tweak_add(bytes(32), bytes(32))
    with pytest.raises(AssertionError, match="reached libsecp256k1"):
        libsecp256k1_xonly.prvkey_tweak_add(bytes(32), bytes(32))

    assert (
        output_pubkey(pub_key, script_tree),
        output_prvkey(prv_key, script_tree),
    ) == delegated


def test_the_python_commitment_check_is_the_bindings_one(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The control block verdict, taken twice, is the same verdict.

    Both verdicts, because a check that only ever says True is a check
    that says nothing: the false one is the same output key with a byte
    flipped, which commits to nothing and must fail on either path.
    """
    pub_key = mult(0xC0FFEE)
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    q = output_pubkey(pub_key, script_tree)[0]
    not_q = bytes([q[0] ^ 1]) + q[1:]
    script, control = input_script_sig(pub_key, script_tree, 0)
    script_bytes = serialize(script)

    assert check_output_pubkey(q, script_bytes, control)
    assert not check_output_pubkey(not_q, script_bytes, control)
    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
        assert check_output_pubkey(q, script_bytes, control)
        assert not check_output_pubkey(not_q, script_bytes, control)


def test_check_output_pubkey_of_a_key_that_is_not_32_bytes() -> None:
    """A q of another length is answered, not refused.

    `tweak_add_check` takes 32 bytes and raises for anything else, so
    the dispatch asks for that size and leaves every other q to the
    Python comparison. Which is not a length test but an integer one:
    it says no to a truncated key and yes to a zero-padded one, and
    that second answer is why the dispatch falls through here instead
    of turning the size into a refusal.
    """
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(None, script_tree)[0]
    script, control = input_script_sig(None, script_tree, 0)

    assert not check_output_pubkey(pub_key[:31], serialize(script), control)
    assert check_output_pubkey(b"\x00" + pub_key, serialize(script), control)


def test_check_output_pubkey_of_an_internal_key_that_is_not_a_point(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Both paths refuse an internal key with no y, in the same words.

    libsecp256k1 rejects it while parsing and `ec.y_even_var` while
    lifting it, and the two have to agree on what they raise as well as
    on what they answer, the script engine catching the library's own.
    This call can make them agree on the sentence too, unlike
    `_tweaked_pubkey` given a `sec`: `tweak_add_check` is handed the
    internal key's x alone, so a refusal is about that x and nothing
    else (issue 1218).

    Three shapes, as the tweak's own test has: 5 is no x-coordinate and
    is written as a decimal, p - 1 is no x-coordinate and is written as
    hex, and p is not a field element at all, which `y_even_var` says in
    words of its own.
    """
    for x, err_msg in (
        (5, "invalid x-coordinate: 5"),
        (secp256k1.p - 1, "invalid x-coordinate: FFFFFFFF"),
        (secp256k1.p, r"x-coordinate not in 0\.\.p-1: FFFFFFFF"),
    ):
        control = b"\xc0" + x.to_bytes(32, "big")
        with pytest.raises(BTClibValueError, match=err_msg):
            check_output_pubkey(b"\x00" * 32, b"\x51", control)
        with monkeypatch.context() as no_bindings:
            no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
            with pytest.raises(BTClibValueError, match=err_msg):
                check_output_pubkey(b"\x00" * 32, b"\x51", control)


def test_the_tweak_refuses_an_internal_key_that_is_no_point_alike(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Both arms of the tweak refuse the same internal key the same way.

    The bindings arm hands `tweak_add` octets nothing has proved are a
    point, deliberately (issue 887), so its refusal arrives from C as a
    bare `ValueError` where the arm below raises btclib's own. Which of
    the two answered is a `pip install`, and a caller catching
    `BTClibValueError` is not meant to have to know (issue 1214).

    On the x-only path the sentence agrees too, and it is one sentence
    rather than three: the lift is `point_from_octets`, which wraps both
    of `curve_group.y_var`'s complaints -- an x that is no coordinate and
    an x that is no field element -- in a single "invalid x-coordinate",
    and this arm reproduces what the lift says rather than what the
    lift's own caller would have said. Nothing is lost that the message
    carried: the three cases below are 5, p - 1 and p, and the hex the
    sentence quotes still tells them apart.
    """
    # the whole sentence on the last two, and not a prefix of it: they
    # differ in their final hex group alone, so a pattern stopping short
    # of it matches either message -- which is the discrimination this
    # docstring claims, and the one a truncation silently drops
    head = "FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE"
    for x, err_msg in (
        (5, "invalid x-coordinate: '05'"),
        (secp256k1.p - 1, f"invalid x-coordinate: '{head} FFFFFC2E'"),
        (secp256k1.p, f"invalid x-coordinate: '{head} FFFFFC2F'"),
    ):
        x_only = x.to_bytes(32, "big")
        with pytest.raises(BTClibValueError, match=err_msg):
            output_pubkey_from_merkle_root(x_only, b"")
        with monkeypatch.context() as no_bindings:
            no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
            with pytest.raises(BTClibValueError, match=err_msg):
                output_pubkey_from_merkle_root(x_only, b"")


@needs_bindings
def test_the_tweak_names_no_half_of_a_sec_it_cannot_blame(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A sec whose fault is not its x is refused without naming one.

    Marked: the first assertion of each pair is the delegated arm's own
    message, so with no bindings installed there is no such arm to reach
    and nothing to compare the second against.

    `_sec_from_key` leaves the octets unproven for the reason the arm
    itself does, and `bytes_from_octets(pub_key, (33, 65))` is the whole
    of what it checks, so what reaches `tweak_add` can be wrong in more
    than one place. The arm names the x only where the x is the only
    place left, which these three are not:

    - `04 || x || y`, a good x and a y that is not its own. The x is the
      half that is right, and naming it would be false.
    - `05 || x`, a SEC length and no SEC prefix, which is the fault of
      neither coordinate.
    - `02 || x || y`, a compressed prefix at the uncompressed length,
      where the two disagree and neither is wrong on its own.

    The last two are here because they are the two halves of what the
    arm reads to decide -- a length and a prefix -- and without them
    dropping either half would leave this suite green while the arm
    named a valid x.

    The two arms agree on the class here rather than on the sentence.
    With no bindings the refusal is the lift `PubKeyData.point` performs,
    in the curve's own words: the tweak is computed either way, and what
    never happens is the addition it was computed for.
    """
    Q = mult(7)
    x = Q[0].to_bytes(32, "big")
    y_not_x_s = ((Q[1] + 1) % secp256k1.p).to_bytes(32, "big")
    for sec, python_msg in (
        (b"\x04" + x + y_not_x_s, "point not on curve"),
        (b"\x05" + x, "not a point: prefix 0x05"),
        (b"\x02" + x + Q[1].to_bytes(32, "big"), "invalid size for compressed point"),
    ):
        with pytest.raises(BTClibValueError, match="invalid internal public key"):
            output_pubkey(sec)
        with monkeypatch.context() as no_bindings:
            no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
            with pytest.raises(BTClibValueError, match=python_msg):
                output_pubkey(sec)


@needs_bindings
@pytest.mark.parametrize("prefix", [0x06, 0x07], ids=["0x06", "0x07"])
def test_a_hybrid_internal_key_is_refused_on_both_arms(
    prefix: int, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A hybrid internal key is refused, not a spelling one arm alone parses.

    Marked, as the test above is, for the same reason: with no bindings
    installed there is no delegated arm to compare the second assertion
    of each pair against.

    libsecp256k1's `ec_pubkey_parse` takes 0x06 and 0x07 as it takes
    0x04, and `sec_point.point_from_octets`'s own lift defaults
    `hybrid=False` -- unrefused, that asymmetry is issue #1227: which
    internal keys `output_pubkey` and `input_script_sig` take would be
    `pip install`'s decision rather than btclib's. The refusal in
    `_output_pubkey_and_internal_key` runs above the arm split, so this
    is one message on both arms rather than a silent accept on one and
    `point_from_octets`'s own "not a point: prefix 0x0…" on the other.

    Both prefixes, because `hybrid=True` reads them asymmetrically once
    a caller does ask for them -- 0x06 names an even y and 0x07 an odd
    one -- and this refusal is meant to run before that reading, on
    either one.
    """
    Q = mult(7)
    sec = bytes([prefix]) + Q[0].to_bytes(32, "big") + Q[1].to_bytes(32, "big")
    with pytest.raises(BTClibValueError, match="hybrid SEC prefix"):
        output_pubkey(sec)
    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
        with pytest.raises(BTClibValueError, match="hybrid SEC prefix"):
            output_pubkey(sec)


@pytest.mark.parametrize("spelling", [bytes, bytearray, memoryview])
def test_check_output_pubkey_takes_every_buffer_the_door_accepts(
    spelling: Callable[[bytes], Octets], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Every spelling `bytes_from_octets` takes reaches the same answer.

    A memoryview used to raise a bare `TypeError` from the merkle fold,
    on both arms: `bytes_from_octets` returned every buffer as it came,
    so a slice of the control block stayed a memoryview and would not
    order against the `bytes` digest it is compared with. A bytearray
    was unaffected, ordering against `bytes` where a memoryview does
    not, which is Python's asymmetry rather than this library's --
    and it is why the census in `bool_parameter_test.py` could not see
    this: the wrong spelling is accepted at the door and refused
    halfway (issue 1220).
    """
    tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    q, _ = output_pubkey(0xC0FFEE, tree)
    witness = input_script_sig(0xC0FFEE, tree, 0)
    script, control = serialize(witness[0]), witness[1]

    assert check_output_pubkey(spelling(q), spelling(script), spelling(control))
    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
        assert check_output_pubkey(spelling(q), spelling(script), spelling(control))


def test_invalid_control_block() -> None:
    """Refuse a control block too long or of an invalid length."""
    err_msg = "control block too long"
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x00", b"\x00" * 4130)

    err_msg = "invalid control block length"
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x00", b"\x00" * 100)


def test_a_control_block_size_is_octets_and_not_characters() -> None:
    """`len` of the text spelling counted characters, and let two sizes in.

    The residue check is `(len - 1) % 32`, and it ran on whatever it was
    handed: `"é" * 33` is 33 characters and 66 octets of UTF-8, and
    passed as a control block size; 66 characters of hex are 33 octets
    and were refused. The coercion `check_output_pubkey` does on the
    same argument is what makes the number octets.
    """
    # 33 octets, one leading byte and a merkle path of none, in both
    # spellings of the same block
    assert_valid_control_block(b"\x00" * 33)
    assert_valid_control_block("00" * 33)
    # 65: one byte and one 32-byte merkle path
    assert_valid_control_block(b"\x00" * 65)

    err_msg = "invalid control block size"
    for wrong_size in (b"\x00" * 34, "00" * 34, b"", b"\x00" * 66):
        with pytest.raises(BTClibValueError, match=err_msg):
            assert_valid_control_block(wrong_size)

    # a str that is no hex string reaches the size check no longer, and
    # what is no octets at all is refused rather than measured: `len` of
    # a tuple of 33 ints is 33
    for not_octets in ("é" * 33, "a" * 33):
        with pytest.raises(BTClibValueError, match="invalid hex string: "):
            assert_valid_control_block(not_octets)
    with pytest.raises(BTClibTypeError, match="invalid octets type: tuple"):
        assert_valid_control_block(tuple(range(33)))  # type: ignore[arg-type]


def test_a_leaf_is_named_from_the_start_of_the_tree() -> None:
    """-1 is the last leaf to Python, and was answered as one.

    `tree_helper(script_tree)[0][script_num]` is a list index, so a
    negative one selected a leaf from the other end and built a control
    block that correctly proves it: the caller asked for a leaf that
    does not exist and got a valid script-path spend of another one.
    """
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    assert input_script_sig(None, script_tree, 0)[0] == ["OP_2"]
    assert input_script_sig(None, script_tree, 1)[0] == ["OP_3"]

    for out_of_range in (-1, -2, 2, 99):
        with pytest.raises(BTClibValueError, match="invalid leaf index: "):
            input_script_sig(None, script_tree, out_of_range)
    for not_an_index in (1.0, "1", True):
        with pytest.raises(BTClibTypeError, match="invalid leaf index type: "):
            input_script_sig(None, script_tree, not_an_index)  # type: ignore[arg-type]


def test_unspendable_script() -> None:
    """Refuse output_pubkey with neither a key nor a script tree."""
    err_msg = "missing data"
    with pytest.raises(BTClibValueError, match=err_msg):
        output_pubkey()


def test_control_block() -> None:
    """Verify input_script_sig's control block passes the BIP341 check."""
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(None, script_tree)[0]
    script, control = input_script_sig(None, script_tree, 0)
    assert check_output_pubkey(pub_key, serialize(script), control)

    prv_key = 123456
    internal_pubkey = mult(prv_key)
    script_tree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(internal_pubkey, script_tree)[0]
    script, control = input_script_sig(internal_pubkey, script_tree, 0)
    assert check_output_pubkey(pub_key, serialize(script), control)


def test_the_two_output_keys_are_one_tweak() -> None:
    """A tree and its own merkle root reach the same output key.

    Which is the whole claim of `output_pubkey_from_merkle_root`: it is
    `output_pubkey` with the root already computed, the form a psbt
    carries it in. Both halves of BIP341's tweak are checked -- the key
    path, where the root is empty, and a tree, whose root comes from
    `tree_helper`.

    The unspendable internal key `output_pubkey` substitutes for a
    missing one is not this function's business: the psbt field it
    serves is either present or the input says nothing to check.
    """
    internal_pubkey = mult(123456)
    x_only = bytes_from_point(internal_pubkey)[1:]
    assert output_pubkey_from_merkle_root(x_only) == output_pubkey(internal_pubkey)

    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    merkle_root = tree_helper(script_tree)[1]
    assert output_pubkey_from_merkle_root(x_only, merkle_root) == (
        output_pubkey(internal_pubkey, script_tree)
    )

    # a memoryview x, which `bytes_from_octets` coerces: `memoryview +
    # bytes` is not an operation at all, and this function prefixes an
    # `02` to the x it was given. The internal key of `output_pubkey`
    # passes the same coercion one layer lower, in `PubKeyData`, so this
    # entry point needs its own assertion rather than that one's
    assert output_pubkey_from_merkle_root(memoryview(x_only), merkle_root) == (
        output_pubkey(internal_pubkey, script_tree)
    )


def test_the_two_output_prvkeys_are_one_tweak() -> None:
    """A tree and its own merkle root tweak a private key the same way.

    The private counterpart of `test_the_two_output_keys_are_one_tweak`:
    a `KeyManager` signing a taproot key path spend has the merkle root
    a psbt carries and not the tree that produced it, and this is what
    tweaks a private key from the one it is given.
    """
    prv_key = 123456
    assert output_prvkey_from_merkle_root(prv_key) == output_prvkey(prv_key)

    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    merkle_root = tree_helper(script_tree)[1]
    assert output_prvkey_from_merkle_root(prv_key, merkle_root) == output_prvkey(
        prv_key, script_tree
    )


# the vector's scriptTree, not a tree: nested json lists of
# {"leafVersion": ..., "script": ...} objects, hence Any in and a real
# TaprootScriptTree out -- each leaf a tuple, the one shape the alias
# names, not a two-element list that happens to unpack the same way
def convert_script_tree(script_tree: Any) -> TaprootScriptTree:
    """Convert a vector's scriptTree json into a TaprootScriptTree."""
    if isinstance(script_tree, list):
        return [convert_script_tree(x) for x in script_tree]
    if isinstance(script_tree, dict):
        return [(script_tree["leafVersion"], parse(script_tree["script"]))]
    return []


@pytest.mark.parametrize(
    "test",
    [
        pytest.param(test, id=vector_id(index, test["given"]["internalPubkey"][:16]))
        for index, test in enumerate(
            load("script", "_data", "taproot_test_vector.json")["scriptPubKey"]
        )
    ],
)
def test_bip_test_vector(test: dict[str, Any]) -> None:
    """Reproduce bip-0341's wallet vectors: tweaked key and address."""
    pub_key = test["given"]["internalPubkey"]
    script_tree = convert_script_tree(test["given"]["scriptTree"])

    tweaked_pubkey = output_pubkey(f"02{pub_key}", script_tree)[0]
    address = b32.p2tr(tweaked_pubkey)

    assert tweaked_pubkey.hex() == test["intermediary"]["tweakedPubkey"]
    assert address == test["expected"]["bip350Address"]


def test_serialize_op_success() -> None:
    """Parse an OP_SUCCESS byte, with and without exit_on_op_success."""
    assert parse(b"\x01\x00\x7e", exit_on_op_success=True) == ["OP_SUCCESS"]

    assert parse(b"\x7e\x02\x01") == ["OP_SUCCESS126", b"\x02\x01"]


def test_serialize_bytes_command() -> None:
    """Verify the push-length encoding grows at 76 and 256 bytes."""
    length = 75
    b = b"\x0a" * length
    assert len(serialize([b])) == length + 1
    b = b"\x0a" * (length + 1)
    assert len(serialize([b])) == (length + 1) + 2

    length = 255
    b = b"\x0a" * length
    assert len(serialize([b])) == length + 2
    b = b"\x0a" * (length + 1)
    assert len(serialize([b])) == (length + 1) + 3


def test_invalid_serialization() -> None:
    """Refuse a non-hex push and an OP_SUCCESS not followed by bytes."""
    with pytest.raises(BTClibValueError):
        serialize(["AAA"])

    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80"])

    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80", 1])
    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80", "00"])


def test_op_success_is_followed_by_bytes_however_they_are_held() -> None:
    """The refusal is about the command's kind, not about how it is held.

    `Command` names every buffer, so the push after an OP_SUCCESS is one
    whether it arrives as bytes or as a slice of a larger field, and all
    three write the same script. Asked because the check that guards
    this branch reads `isinstance(script[0], ...)` and a list of types
    is what stops being the answer when the alias gains a spelling: a
    bytearray drew "OP_SUCCESS must be followed by a single bytes
    command" about a command that is a single bytes command
    (issue #1238).
    """
    push = b"\x01\x02\x03"
    expected = serialize(["OP_SUCCESS80", push])
    for spelling in (bytearray(push), memoryview(push)):
        assert serialize(["OP_SUCCESS80", spelling]) == expected


def test_parse_unknown_op_code() -> None:
    """0xff is neither an OP_SUCCESS nor a named op code."""
    with pytest.raises(BTClibValueError, match="unknown op code: 0xff"):
        parse(b"\xff")


def test_serialization() -> None:
    """Round-trip scripts, small integers as data pushes included."""
    script: ScriptList = ["OP_SUCCESS80", b"\x01\x01\x01"]
    assert parse(serialize(script)) == script

    # -1 and [1, 16] are the integers whose one-byte op code the data
    # push is not, so every serialize() below pushes data where an op
    # code would do and warns; zero's encoding is the empty vector, so
    # its push is that op code and it warns not
    assert parse(serialize_non_canonical([-1], serialize)) == ["81"]
    for x in range(1, 17):
        assert parse(serialize_non_canonical([x], serialize)) == [f"{x:02X}"]
    assert parse(serialize([0])) == ["OP_0"]

    for x in range(17, 100):
        assert parse(serialize([x])) == [f"{x:02X}"]


def test_tweak_above_group_order(monkeypatch: pytest.MonkeyPatch) -> None:
    """BIP341 rejects a tweak t that is not below the curve order.

    On secp256k1 that is a 2**-128 tagged-hash accident, so the guard is
    reached by patching what stands in the way rather than left
    uncovered: a toy curve, whose order a 256-bit tweak always exceeds,
    put where `_tap_tweak` reads `secp256k1.n`.

    The patch replaced an `ec` argument these functions used to take
    (issue #618). It is the same toy curve doing the same work, from the
    other side of the call, and it stops there: `_tap_tweak` raises
    before any arithmetic, so nothing downstream sees the substitution.
    `output_prvkey` is still not among them, its own path reaching the y
    parity of a secp256k1 point first.
    """
    monkeypatch.setattr(taproot, "secp256k1", low_card_curves["ec13_11"])
    err_msg = "Invalid script tree hash"

    script_tree: TaprootScriptTree = [(0xC0, ["OP_1"])]
    with pytest.raises(BTClibValueError, match=err_msg):
        output_pubkey(None, script_tree)

    q = bytes(31) + b"\x01"
    control = b"\xc0" + bytes(32)
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(q, "51", control)


def test_the_element_size_limit_is_reachable_not_only_crossable() -> None:
    """520 bytes is an element a tapscript may push; 521 is one too many.

    BIP342 keeps the limit script.parse enforces and moves the refusal:
    an OP_SUCCESS makes a script valid whatever else it holds, so the
    parse notes the oversized element and raises only if it reaches the
    end without meeting one. What that leaves to test is the bound
    itself, from both sides -- a limit tested above only is a limit
    whose own value never mattered.
    """
    for size in (MAX_SCRIPT_ELEMENT_SIZE - 1, MAX_SCRIPT_ELEMENT_SIZE):
        data = b"\x00" * size
        script = b"\x4d" + size.to_bytes(2, "little") + data
        assert parse(script) == [data.hex().upper()]

    size = MAX_SCRIPT_ELEMENT_SIZE + 1
    script = b"\x4d" + size.to_bytes(2, "little") + b"\x00" * size
    err_msg = "Invalid pushdata length"
    with pytest.raises(BTClibValueError, match=err_msg):
        parse(script)

    # and the same element under an OP_SUCCESS, which is valid: 0x50 is
    # OP_SUCCESS80, and what follows one is not parsed at all
    assert parse(b"\x50" + script) == ["OP_SUCCESS80", script]


@pytest.mark.parametrize("internal_key", [0xC0FFEE, 0xBADC0DE])
def test_the_control_block_commits_to_the_output_key_parity(
    internal_key: int, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The lowest bit of the first control byte is the output key's parity.

    The rest of that byte is the leaf version, which the leaf hash reads
    with the parity bit masked off, so flipping it leaves every hash in
    the proof alone and changes only the claim about which of the two y
    coordinates the output key has. Both paths compare it --
    libsecp256k1's `tweak_add_check` takes it as an argument and the
    Python one against Q's own y -- and a wrong claim has to be a no on
    each.

    Two internal keys because the output key's parity is what it is:
    0xC0FFEE tweaks to an even y and 0xBADC0DE to an odd one, so between
    them the bit is asserted in both directions rather than in whichever
    one this tree happens to produce.
    """
    pub_key = mult(internal_key)
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    q, parity = output_pubkey(pub_key, script_tree)
    script, control = input_script_sig(pub_key, script_tree, 0)
    script_bytes = serialize(script)
    assert control[0] & 1 == parity
    flipped = bytes([control[0] ^ 1]) + control[1:]

    assert check_output_pubkey(q, script_bytes, control)
    assert not check_output_pubkey(q, script_bytes, flipped)
    with monkeypatch.context() as no_bindings:
        no_bindings.setattr(taproot, "_libsecp256k1_serves", lambda *_: False)
        assert check_output_pubkey(q, script_bytes, control)
        assert not check_output_pubkey(q, script_bytes, flipped)
