#!/usr/bin/env python3

# Copyright (C) The btclib developers
#
# This file is part of btclib. It is subject to the license terms in the
# LICENSE file found in the top-level directory of this distribution.
#
# No part of btclib including this file, may be copied, modified, propagated,
# or distributed except according to the terms contained in the LICENSE file.
"""Tests for the `btclib.script.taproot` module.

The same two vendored files as `test_sig_hash_taproot.py`, and the same
distinction: `taproot_test_vector.json` is bip-0341's
`wallet-test-vectors.json`, while `script_assets_test.json` keeps the name
it has in `unit_test_data/` of bitcoin-core/qa-assets, a dump generated by
Core rather than anything a BIP publishes.
tests/_data/README.md pins the revision of each.
"""

from typing import Any

import pytest

from btclib import b32
from btclib.alias import ScriptList
from btclib.curves import mult
from btclib.exceptions import BTClibValueError
from btclib.script import (
    TaprootScriptTree,
    Witness,
    check_output_pubkey,
    input_script_sig,
    is_p2tr,
    output_prvkey,
    output_pubkey,
    type_and_payload,
)
from btclib.script.taproot import parse, serialize
from btclib.tx import TxOut
from tests import vectors
from tests.curves.test_curve import low_card_curves
from tests.script import serialize_non_canonical


def script_path_vectors() -> list[Any]:
    """The vectors spending a p2tr prevout through a script path.

    The two `continue` of the loop: a prevout that is not p2tr, and a
    witness with nothing but a signature on it once the annex is off.
    """
    params = []
    for index, x in enumerate(
        vectors.load("script", "_data", "script_assets_test.json")
    ):
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) >= 2 and stack[-1][0] == 0x50:
            stack = stack[:-1]  # drop the annex
        if len(stack) < 2:
            continue
        params.append(pytest.param(x, id=vectors.vector_id(index, x["comment"])))
    return params


@pytest.mark.parametrize("vector", script_path_vectors())
def test_valid_script_path(vector: dict[str, Any]) -> None:
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    assert not vector["success"]["scriptSig"]

    witness = Witness(vector["success"]["witness"])
    if len(witness.stack) >= 2 and witness.stack[-1][0] == 0x50:
        witness = Witness(witness.stack[:-1])  # drop the annex

    Q = type_and_payload(prevouts[index].script_pub_key.script)[1]

    script = witness.stack[-2]
    control = witness.stack[-1]

    assert check_output_pubkey(Q, script, control)


def test_taproot_key_tweaking() -> None:
    prv_key = 123456
    pub_key = mult(prv_key)

    script_trees: list[TaprootScriptTree | None] = [
        None,
        [(0xC0, ["OP_1"])],
        [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]],
    ]

    for script_tree in script_trees:
        tweaked_prvkey = output_prvkey(prv_key, script_tree)
        tweaked_pubkey = output_pubkey(pub_key, script_tree)[0]

        assert tweaked_pubkey == mult(tweaked_prvkey)[0].to_bytes(32, "big")


def test_invalid_control_block() -> None:
    err_msg = "control block too long"
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x00", b"\x00" * 4130)

    err_msg = "invalid control block length"
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(b"\x00" * 32, b"\x00", b"\x00" * 100)


def test_unspendable_script() -> None:
    err_msg = "missing data"
    with pytest.raises(BTClibValueError, match=err_msg):
        output_pubkey()


def test_control_block() -> None:
    script_tree: TaprootScriptTree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(None, script_tree)[0]
    script, control = input_script_sig(None, script_tree, 0)
    assert check_output_pubkey(pub_key, serialize(script), control)

    prv_key = 123456
    internal_pubkey = mult(prv_key)
    script_tree = [[(0xC0, ["OP_2"])], [(0xC0, ["OP_3"])]]
    pub_key = output_pubkey(internal_pubkey, script_tree)[0]
    script, control = input_script_sig(internal_pubkey, script_tree, 0)
    assert check_output_pubkey(pub_key, serialize(script), control)


# the vector's scriptTree, not a tree: nested json lists of
# {"leafVersion": ..., "script": ...} objects, hence Any in and a real
# TaprootScriptTree out. It used to be annotated TaprootScriptTree both
# ways, which said nothing while the alias was Any -- and it built each
# leaf as a two-element list, where every other caller writes the pair as
# a tuple. Both shapes unpack, so nothing failed; the alias now picks one
def convert_script_tree(script_tree: Any) -> TaprootScriptTree:
    if isinstance(script_tree, list):
        return [convert_script_tree(x) for x in script_tree]
    if isinstance(script_tree, dict):
        return [(script_tree["leafVersion"], parse(script_tree["script"]))]
    return []


@pytest.mark.parametrize(
    "test",
    [
        pytest.param(
            test, id=vectors.vector_id(index, test["given"]["internalPubkey"][:16])
        )
        for index, test in enumerate(
            vectors.load("script", "_data", "taproot_test_vector.json")["scriptPubKey"]
        )
    ],
)
def test_bip_test_vector(test: dict[str, Any]) -> None:
    pub_key = test["given"]["internalPubkey"]
    script_tree = convert_script_tree(test["given"]["scriptTree"])

    tweaked_pubkey = output_pubkey(f"02{pub_key}", script_tree)[0]
    address = b32.p2tr(tweaked_pubkey)

    assert tweaked_pubkey.hex() == test["intermediary"]["tweakedPubkey"]
    assert address == test["expected"]["bip350Address"]


def test_serialize_op_success() -> None:
    assert parse(b"\x01\x00\x7e", exit_on_op_success=True) == ["OP_SUCCESS"]

    assert parse(b"\x7e\x02\x01") == ["OP_SUCCESS126", b"\x02\x01"]


def test_serialize_bytes_command() -> None:
    length = 75
    b = b"\x0a" * length
    assert len(serialize([b])) == length + 1
    b = b"\x0a" * (length + 1)
    assert len(serialize([b])) == (length + 1) + 2

    length = 255
    b = b"\x0a" * length
    assert len(serialize([b])) == length + 2
    b = b"\x0a" * (length + 1)
    assert len(serialize([b])) == (length + 1) + 3


def test_invalid_serialization() -> None:
    with pytest.raises(BTClibValueError):
        serialize(["AAA"])

    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80"])

    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80", 1])
    with pytest.raises(BTClibValueError, match="OP_SUCCESS must be followed"):
        serialize(["OP_SUCCESS80", "00"])


def test_parse_unknown_op_code() -> None:
    """0xff is neither an OP_SUCCESS nor a named op code."""
    with pytest.raises(BTClibValueError, match="unknown op code: 0xff"):
        parse(b"\xff")


def test_serialization() -> None:
    script: ScriptList = ["OP_SUCCESS80", b"\x01\x01\x01"]
    assert parse(serialize(script)) == script

    # -1 and [0, 16] are the integers with a one-byte op code, so every
    # serialize() below pushes data where an op code would do and warns
    assert parse(serialize_non_canonical([-1], serialize)) == ["81"]
    for x in range(17):
        assert parse(serialize_non_canonical([x], serialize)) == [f"{x:02X}"]

    for x in range(17, 100):
        assert parse(serialize([x])) == [f"{x:02X}"]


def test_tweak_above_group_order() -> None:
    """BIP341 rejects a tweak t that is not below the curve order.

    With secp256k1 that is a 2**-128 tagged-hash accident; a toy curve
    makes the same guard fire deterministically, since the 256-bit
    tweak always exceeds its order. Not output_prvkey, though: there
    the toy curve fails earlier, on the y parity of a secp256k1 point.
    """
    ec = low_card_curves["ec13_11"]
    err_msg = "Invalid script tree hash"

    script_tree: TaprootScriptTree = [(0xC0, ["OP_1"])]
    with pytest.raises(BTClibValueError, match=err_msg):
        output_pubkey(None, script_tree, ec)

    q = bytes(31) + b"\x01"
    control = b"\xc0" + bytes(32)
    with pytest.raises(BTClibValueError, match=err_msg):
        check_output_pubkey(q, "51", control, ec)
