#!/usr/bin/env python3

# Copyright (C) The btclib developers
#
# This file is part of btclib. It is subject to the license terms in the
# LICENSE file found in the top-level directory of this distribution.
#
# No part of btclib including this file, may be copied, modified, propagated,
# or distributed except according to the terms contained in the LICENSE file.
"""Tests for the `btclib.sig_hash` module.

Two vendored files, from two upstreams, and the bip-0341 citation this
docstring used to carry covered only one of them:

- `taproot_test_vector.json` is bip-0341's `wallet-test-vectors.json`,
  https://github.com/bitcoin/bips/blob/master/bip-0341/wallet-test-vectors.json
- `script_assets_test.json` is *not* in a BIP. It is
  `unit_test_data/script_assets_test.json` of bitcoin-core/qa-assets --
  upstream's own name, kept -- generated by Core's
  `test/functional/feature_taproot.py --dumptests`, which is why bip-0341
  does not lead to it.

tests/_data/README.md pins the revision of each.
"""

from typing import Any

import pytest

from btclib.alias import ScriptList
from btclib.ecc import ssa
from btclib.exceptions import BTClibRuntimeError, BTClibValueError
from btclib.hashes import hash160
from btclib.script import (
    ScriptPubKey,
    Witness,
    is_p2tr,
    output_prvkey,
    parse,
    serialize,
    sig_hash,
    type_and_payload,
)
from btclib.script.engine import verify_transaction
from btclib.tx import OutPoint, Tx, TxIn, TxOut
from tests import vectors

TAPSCRIPT = vectors.load("script", "_data", "script_assets_test.json")


def is_key_path(witness: Witness) -> bool:
    """A key path spend: the signature alone, or the signature and an annex."""
    stack = witness.stack
    return len(stack) == 1 or (len(stack) == 2 and stack[-1][0] == 0x50)


def key_path_vectors(outcome: str, taproot_flag: bool) -> list[Any]:
    """The vectors of `outcome` that spend a p2tr prevout through the key path.

    Selecting them here rather than skipping the others with `continue`
    inside the test is what makes the count in the report the count of
    what ran: of the 2243 vectors in the file, three quarters are not
    key path spends, and the loop used to report 1 test either way.

    The parse of every prevout is the price, paid once per worker at
    collection: 3 ms for the file.
    """
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if outcome not in x or (taproot_flag and "TAPROOT" not in x["flags"]):
            continue
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        if not is_key_path(Witness(x[outcome]["witness"])):
            continue
        params.append(pytest.param(x, id=vectors.vector_id(index, x["comment"])))
    return params


@pytest.mark.parametrize("vector", key_path_vectors("success", taproot_flag=True))
def test_valid_taproot_key_path(vector: dict[str, Any]) -> None:
    tx = Tx.parse(vector["tx"])
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    assert not vector["success"]["scriptSig"]

    witness = Witness(vector["success"]["witness"])
    tx.vin[index].script_witness = witness

    sighash_type = 0  # all
    signature = witness.stack[0][:64]
    if len(witness.stack[0]) == 65:
        sighash_type = witness.stack[0][-1]
        assert sighash_type != 0

    msg_hash = sig_hash.from_tx(prevouts, tx, index, sighash_type)

    pub_key = type_and_payload(prevouts[index].script_pub_key.script)[1]

    ssa.assert_as_valid_(msg_hash, pub_key, signature)


# the failure vectors are taken whatever their flags, as they were: a
# vector that does not ask for TAPROOT still must not verify
@pytest.mark.parametrize("vector", key_path_vectors("failure", taproot_flag=False))
def test_invalid_taproot_key_path(vector: dict[str, Any]) -> None:
    tx = Tx.parse(vector["tx"])
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]

    witness = Witness(vector["failure"]["witness"])
    tx.vin[index].script_witness = witness

    with pytest.raises((BTClibRuntimeError, BTClibValueError, AssertionError)):
        assert not vector["failure"]["scriptSig"]

        sighash_type = 0  # all
        signature = witness.stack[0][:64]
        if len(witness.stack[0]) == 65:
            sighash_type = witness.stack[0][-1]
            if sighash_type == 0:
                raise BTClibValueError("invalid sighash 0 in 65 bytes signature")

        msg_hash = sig_hash.from_tx(prevouts, tx, index, sighash_type)

        pub_key = type_and_payload(prevouts[index].script_pub_key.script)[1]

        ssa.assert_as_valid_(msg_hash, pub_key, signature)


def test_valid_taproot_script_path() -> None:
    tx_data = "26dc279d02d8b1a203b653fc4e0f27f408432f3f540136d33f8f930eaeba655910095142980402000000fd697cd4eb5278f1e34545cd57b6670df806fa3a0a064fd8e385a19f1a53d9ce8d8971a30f02000000378d5fb502335dbe02000000001976a9140053a23441c8478caac4c6b769c51f8476cd4b4b88ac58020000000000001976a914f2aae94a43e0d173354201d7832b46c5269c8a2488ac4a08671e"
    prevouts_data = [
        "91ca4c010000000017a9145658b58602cdf7b7e962cfe44e024cb0e366f27087",
        "cb127401000000002251201ebe8b90363bd097aa9f352c8b21914e1886bc09fe9e70c09f33ef2d2abdf4bc",
    ]
    witness_data = [
        "9675a9982c6398ea9d441cb7a943bcd6ff033cc3a2e01a0178a7d3be4575be863871c6bf3eef5ecd34721c784259385ca9101c3a313e010ac942c99de05aaaa602",
        "5799cf4b193b730fb99580b186f7477c2cca4d28957326f6f1a5d14116438530e7ec0ce1cd465ad96968ae8a6a09d4d37a060a115919f56fcfebe7b2277cc2df5cc08fb6cda9105ee2512b2e22635aba",
        "7520c7b5db9562078049719228db2ac80cb9643ec96c8055aa3b29c2c03d4d99edb0ac",
        "c1a7957acbaaf7b444c53d9e0c9436e8a8a3247fd515095d66ddf6201918b40a3668f9a4ccdffcf778da624dca2dda0b08e763ec52fd4ad403ec7563a3504d0cc168b9a77a410029e01dac89567c9b2e6cd726e840351df3f2f58fefe976200a19244150d04153909f660184d656ee95fa7bf8e1d4ec83da1fca34f64bc279b76d257ec623e08baba2cfa4ea9e99646e88f1eb1668c00c0f15b7443c8ab83481611cc3ae85eb89a7bfc40067eb1d2e6354a32426d0ce710e88bc4cc0718b99c325509c9d02a6a980d675a8969be10ee9bef82cafee2fc913475667ccda37b1bc7f13f64e56c449c532658ba8481631c02ead979754c809584a875951619cec8fb040c33f06468ae0266cd8693d6a64cea5912be32d8de95a6da6300b0c50fdcd6001ea41126e7b7e5280d455054a816560028f5ca53c9a50ee52f10e15c5337315bad1f5277acb109a1418649dc6ead2fe14699742fee7182f2f15e54279c7d932ed2799d01d73c97e68bbc94d6f7f56ee0a80efd7c76e3169e10d1a1ba3b5f1eb02369dc43af687461c7a2a3344d13eb5485dca29a67f16b4cb988923060fd3b65d0f0352bb634bcc44f2fe668836dcd0f604150049835135dc4b4fbf90fb334b3938a1f137eb32f047c65b85e6c1173b890b6d0162b48b186d1f1af8521945924ac8ac8efec321bf34f1d4b3d4a304a10313052c652d53f6ecb8a55586614e8950cde9ab6fe8e22802e93b3b9139112250b80ebc589aba231af535bb20f7eeec2e412f698c17f3fdc0a2e20924a5e38b21a628a9e3b2a61e35958e60c7f5087c",
    ]

    tx = Tx.parse(tx_data)
    prevouts = [TxOut.parse(prevout) for prevout in prevouts_data]
    index = 1
    witness = Witness(witness_data)
    tx.vin[index].script_witness = witness

    sighash_type = 0  # all
    signature = witness.stack[0][:64]
    if len(witness.stack[0]) == 65:
        sighash_type = witness.stack[0][-1]
        assert sighash_type != 0

    msg_hash = sig_hash.from_tx(prevouts, tx, index, sighash_type)

    tapscript = parse(witness.stack[-2])
    pub_key = bytes.fromhex(str(tapscript[1]))

    ssa.assert_as_valid_(msg_hash, pub_key, signature)


def test_valid_sighash_type() -> None:
    for hash_type in range(256):
        if hash_type in sig_hash.SIG_HASH_TYPES:
            sig_hash.assert_valid_hash_type(hash_type)
        else:
            err_msg = "invalid sig_hash type: "
            with pytest.raises(BTClibValueError, match=err_msg):
                sig_hash.assert_valid_hash_type(hash_type)


def test_empty_stack() -> None:
    utxo = TxOut(
        100000000,
        serialize(
            ["OP_1", "cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaf"]
        ),
    )
    tx_in = TxIn(OutPoint(), "5151", 1, Witness([]))
    tx = Tx(vin=[tx_in], vout=[TxOut(100000000, "")])

    err_msg = "Empty stack"
    with pytest.raises(BTClibValueError, match=err_msg):
        sig_hash.from_tx([utxo], tx, 0, 0)


def test_wrapped_p2tr() -> None:
    script: ScriptList = [
        "OP_1",
        "cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaf",
    ]
    utxo = TxOut(
        100000000, serialize(["OP_HASH160", hash160(serialize(script)), "OP_EQUAL"])
    )
    # the script_sig pushes the redeem script, it is not the redeem script
    script_sig = serialize([serialize(script)])
    tx_in = TxIn(OutPoint(), script_sig, 1, Witness(["0A" * 32]))
    tx = Tx(vin=[tx_in], vout=[TxOut(100000000, "")])

    err_msg = "Taproot scripts cannot be wrapped in p2sh"
    with pytest.raises(BTClibValueError, match=err_msg):
        sig_hash.from_tx([utxo], tx, 0, 0)


def annex_vectors() -> list[Any]:
    """The vectors whose witness carries an annex: nothing else can strip one."""
    params = []
    for index, x in enumerate(TAPSCRIPT):
        if "TAPROOT" not in x["flags"]:
            continue
        prevouts = [TxOut.parse(prevout) for prevout in x["prevouts"]]
        if not is_p2tr(prevouts[x["index"]].script_pub_key.script):
            continue
        stack = Witness(x["success"]["witness"]).stack
        if len(stack) < 2 or stack[-1][0] != 0x50:
            continue  # no annex, nothing to strip
        params.append(pytest.param(x, id=vectors.vector_id(index, x["comment"])))
    return params


ANNEX_VECTORS = annex_vectors()


def test_annex_vectors_exist() -> None:
    """The test below proves nothing on an empty set of vectors.

    It was the `assert annexed` at the end of the loop; a parametrized
    test over no parameter is reported as one green skip, so the count
    is asserted here rather than not at all.
    """
    assert ANNEX_VECTORS


@pytest.mark.parametrize("vector", ANNEX_VECTORS)
def test_from_tx_does_not_touch_the_tx(vector: dict[str, Any]) -> None:
    """Computing a taproot sighash must not strip the annex from the Tx.

    `taproot_annex_and_ext` used to assign the trimmed stack back to the
    witness it was handed, so a second call on the same Tx saw no annex and
    hashed a different preimage, while `tx.serialize()` and `tx.hash` changed
    under the caller (issue #140).
    """
    prevouts = [TxOut.parse(prevout) for prevout in vector["prevouts"]]
    index = vector["index"]
    stack = Witness(vector["success"]["witness"]).stack

    tx = Tx.parse(vector["tx"])
    tx.vin[index].script_witness = Witness(stack)
    serialized = tx.serialize(include_witness=True, check_validity=False)

    msg_hash = sig_hash.from_tx(prevouts, tx, index, 0)

    assert sig_hash.from_tx(prevouts, tx, index, 0) == msg_hash
    assert tx.vin[index].script_witness.stack == stack
    assert tx.serialize(include_witness=True, check_validity=False) == serialized


KEY_PATH_SPENDING = vectors.load("script", "_data", "taproot_test_vector.json")[
    "keyPathSpending"
][0]


def unsigned_tx_and_utxos() -> tuple[Tx, list[TxOut]]:
    """The BIP341 key path spending case, rebuilt for each of its inputs.

    Rebuilt rather than shared: a parameter is one object handed to every
    test that takes it, and this Tx is the argument of the very calls the
    module tests for mutating it.
    """
    tx = Tx.parse(KEY_PATH_SPENDING["given"]["rawUnsignedTx"])
    utxos = [
        TxOut(utxo["amountSats"], utxo["scriptPubKey"])
        for utxo in KEY_PATH_SPENDING["given"]["utxosSpent"]
    ]
    for vin in tx.vin:
        # a new Witness, the stack being an immutable tuple
        vin.script_witness = Witness([*vin.script_witness.stack, b"00"])
    return tx, utxos


@pytest.mark.parametrize(
    "spending",
    [
        pytest.param(
            spending,
            id=vectors.vector_id(
                index,
                f"input{spending['given']['txinIndex']}",
                f"hashtype{spending['given']['hashType']}",
            ),
        )
        for index, spending in enumerate(KEY_PATH_SPENDING["inputSpending"])
    ],
)
def test_bip_test_vector(spending: dict[str, Any]) -> None:
    unsigned_tx, utxos = unsigned_tx_and_utxos()

    index = spending["given"]["txinIndex"]
    hash_type = spending["given"]["hashType"]
    signature_hash = sig_hash.from_tx(utxos, unsigned_tx, index, hash_type)
    assert signature_hash.hex() == spending["intermediary"]["sigHash"]

    # and now sign it, which is the half of these vectors the suite used
    # to leave on the table: the sigHash was checked and "expected", the
    # witness the BIP says that hash signs to, was not. aux_rand of 32
    # zero bytes is what BIP341 made them with, and pinning it is what
    # makes a BIP340 signature reproducible at all
    tweaked_prv_key = bytes.fromhex(spending["intermediary"]["tweakedPrivkey"])
    signature = ssa.sign_(signature_hash, tweaked_prv_key, b"\x00" * 32)
    witness_element = signature.serialize()
    # SIGHASH_DEFAULT is the 64-byte form: the type is appended only when
    # it is not the default one, and 0x00 appended is invalid (issue #122)
    if hash_type != sig_hash.DEFAULT:
        witness_element += hash_type.to_bytes(1, "big")
    assert witness_element.hex() == spending["expected"]["witness"][0]

    # verified the way issue 124 verified it, which is the correct way:
    # the key is the x-only *output* key the script carries, and the
    # message is the sig_hash itself -- hence assert_as_valid_ and sign_,
    # the spellings that do not reduce their argument with hf
    pub_key = type_and_payload(utxos[index].script_pub_key.script)[1]
    ssa.assert_as_valid_(signature_hash, pub_key, signature)

    # btclib's own tweak against the BIP's number, for the one input that
    # commits to no script: output_prvkey takes the tree, and these
    # vectors give a merkle root, so the six that have one are covered by
    # the signature above rather than here
    if spending["given"]["merkleRoot"] is None:
        internal_prv_key = bytes.fromhex(spending["given"]["internalPrivkey"])
        assert output_prvkey(internal_prv_key) == int.from_bytes(tweaked_prv_key, "big")


@pytest.mark.parametrize(
    "hash_type",
    [
        sig_hash.DEFAULT,
        sig_hash.ALL,
        sig_hash.NONE,
        sig_hash.SINGLE,
        sig_hash.ANYONECANPAY | sig_hash.ALL,
    ],
    ids=["default", "all", "none", "single", "anyonecanpay-all"],
)
@pytest.mark.parametrize(
    "script_tree", [None, [(0xC0, ["OP_1"])]], ids=["key only", "script tree"]
)
def test_key_path_spend_round_trip(hash_type: int, script_tree: Any) -> None:
    """Sign a key path spend with btclib and have btclib's engine accept it.

    The BIP341 vectors above are signed and verified against numbers the
    BIP provides; this builds the spend instead, so the tweak, the
    sig_hash, the signature, the witness encoding and the script engine
    are all btclib's. Issue 124 is the reason it exists: nothing here used
    to sign a key path spend end to end, so a caller reading the suite for
    the pattern found the verify half alone -- and the two mistakes below
    are the ones that half invites.
    """
    prv_key = 0x4242424242424242424242424242424242424242424242424242424242424242
    script_pub_key = ScriptPubKey.p2tr(prv_key, script_tree)
    prevouts = [TxOut(100_000, script_pub_key)]

    vin = TxIn(OutPoint(b"\x11" * 32, 0))
    # from_tx reads the witness to tell a key path spend from a script
    # path one, so an unsigned input still needs a placeholder in it
    vin.script_witness = Witness([b"\x00" * 64])
    tx = Tx(vin=[vin], vout=[TxOut(90_000, script_pub_key)])

    msg = sig_hash.from_tx(prevouts, tx, 0, hash_type)
    signature = ssa.sign_(msg, output_prvkey(prv_key, script_tree))
    pub_key = type_and_payload(prevouts[0].script_pub_key.script)[1]
    ssa.assert_as_valid_(msg, pub_key, signature)

    witness_element = signature.serialize()
    if hash_type != sig_hash.DEFAULT:
        witness_element += hash_type.to_bytes(1, "big")
    assert len(witness_element) == (64 if hash_type == sig_hash.DEFAULT else 65)

    # the whole point: the engine, with every flag on, spends the output
    tx.vin[0].script_witness = Witness([witness_element])
    verify_transaction(prevouts, tx)

    # the two ways issue 124 got a "signature verification failed", each
    # on its own. sign reduces its argument with hf and sign_ does not, so
    # the pair that verifies is sign_/assert_as_valid_ (or sign/
    # assert_as_valid, which signs a hash of the sig_hash and is
    # self-consistent rather than valid on the network)
    wrong = ssa.sign(msg, output_prvkey(prv_key, script_tree))
    with pytest.raises(BTClibRuntimeError, match="signature verification failed"):
        ssa.assert_as_valid_(msg, pub_key, wrong)

    # and the key from the script is the tweaked one, the internal key
    # being what the tweak is computed from
    wrong = ssa.sign_(msg, prv_key)
    with pytest.raises(BTClibRuntimeError, match="signature verification failed"):
        ssa.assert_as_valid_(msg, pub_key, wrong)
