name: lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Check linted md
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          command: config
          globs: |
            .markdownlint.jsonc
            **/*.md
      - name: Setup uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - name: Check ruff lint rules
        run: uv run --frozen --no-default-groups --group lint ruff check
      - name: Check ruff formatting
        run: uv run --frozen --no-default-groups --group lint ruff format --check
