name: lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check linted md
        uses: DavidAnson/markdownlint-cli2-action@v8
        with:
          command: config
          globs: |
            .markdownlint.jsonc
            **/*.md
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check isort and black
        run: |
          python -m pip install --upgrade pip isort black
          isort -c .
          black --check .
