name: Python - Test on 3.12-dev

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  experimental:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # 2023-01-01 windows-latest does crash
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12-dev
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: |
          python -m pip install tox
          tox -e py
