name: Python - Test and coverage

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-and-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: |
          python -m pip install tox
          tox -e py
      - name: Coveralls
        run: |
          python -m pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python }}-${{ matrix.os }}
          COVERALLS_PARALLEL: true

  coveralls:
    if: "github.repository == 'btclib-org/btclib' && github.base_ref == 'master'"
    needs: test-and-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Upload to coveralls.io
        run: |
          python -m pip install coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
