name: Python - Check linted code

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  check-py-linted:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check isort and black
        run: |
          python -m pip install -U pip
          python -m pip install -U isort
          isort -c .
          python -m pip install -U black
          black --check .
      - name: Run tox -e lint
        run: |
          python -m pip install tox
          tox -e lint
