name: Python - Test on 3.12-dev

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  experimental:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12-dev
      - name: Install requirements
        run: |
          pip install -U -r requirements-dev.txt
          pip install -U -r requirements.txt
      - name: Run test
        run: pytest
