name: Python - Check linted code

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  check-linted-code:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install requirements
        run: |
          python -m pip install -U -r requirements-dev.txt
          python -m pip install -U -r requirements.txt

      - name: Run linters
        # python setup.py check
        # This repository uses a Markdown long_description, so the -r flag
        # to `setup.py check` is not needed. If your project contains a
        # README.rst, use `python setup.py check -m -r -s` instead.
        #
        # bandit
        # disable B101 (Test for use of assert) on tests folder
        run: |
          isort -c .
          black --check .
          pylint setup.py
          pylint btclib
          pylint tests
          check-manifest
          python setup.py check -m -s
          bandit -r {toxinidir}/btclib
          bandit -s B101 -r {toxinidir}/tests
          flake8 .
          mypy .
