name: py312-dev

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-py312-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # as of 2023-01-01 windows-latest does crash
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12-dev
      - name: Run tox -e py
        run: |
          python -m pip install tox
          tox -e py
